### ISSUE TITLE
StreamingContext Builder error from Ray Streaming Example

### ISSUE THREAD

**Issue by Litchilitchy** [ray-project/ray#11602]
I am using Python 3.6, following code from example [ray stremaing](https://github.com/ray-project/ray/blob/master/streaming/python/examples/wordcount.py)
```
import ray
from ray.streaming import StreamingContext
from ray.streaming.config import Config
import time
import logging


logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)

if __name__ == "__main__":
    # Get program parameters

    ray.init(_load_code_from_local=True)

    ctx = StreamingContext.Builder() \
        .option(Config.CHANNEL_TYPE, Config.NATIVE_CHANNEL) \
        .build()
    # A Ray streaming environment with the default configuration
    ctx.set_parallelism(1)  # Each operator will be executed by two actors
```
The error is raised at build `StreamingContext` line, which is 
```
2020-10-26 09:57:35,776	INFO services.py:1166 -- View the Ray dashboard at http://127.0.0.1:8266
(pid=raylet) F1026 09:57:37.842926  1460  1460 worker_pool.cc:792]  Check failed: state != states_by_lang_.end() Required Language isn't supported.
(pid=raylet) *** Check failure stack trace: ***
(pid=raylet)     @     0x55e9b398c9cd  google::LogMessage::Fail()
(pid=raylet)     @     0x55e9b398db2c  google::LogMessage::SendToLog()
(pid=raylet)     @     0x55e9b398c6a9  google::LogMessage::Flush()
(pid=raylet)     @     0x55e9b398c8c1  google::LogMessage::~LogMessage()
(pid=raylet)     @     0x55e9b3944ad9  ray::RayLog::~RayLog()
(pid=raylet)     @     0x55e9b360978f  ray::raylet::WorkerPool::GetStateForLanguage()
(pid=raylet)     @     0x55e9b360f524  ray::raylet::WorkerPool::PopWorker()
(pid=raylet)     @     0x55e9b365fcea  ray::raylet::NodeManager::DispatchTasks()
(pid=raylet)     @     0x55e9b3661cf6  ray::raylet::NodeManager::EnqueuePlaceableTask()
(pid=raylet)     @     0x55e9b36629c7  ray::raylet::NodeManager::ScheduleTasks()
(pid=raylet)     @     0x55e9b366359e  ray::raylet::NodeManager::SubmitTask()
(pid=raylet)     @     0x55e9b3664194  ray::raylet::NodeManager::HandleRequestWorkerLease()
(pid=raylet)     @     0x55e9b35e5c7c  _ZN5boost4asio6detail18completion_handlerIZN3ray3rpc14ServerCallImplINS4_25NodeManagerServiceHandlerENS4_25RequestWorkerLeaseRequestENS4_23RequestWorkerLeaseReplyEE13HandleRequestEvEUlvE_E11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm
(pid=raylet)     @     0x55e9b3c8a46f  boost::asio::detail::scheduler::do_run_one()
(pid=raylet)     @     0x55e9b3c8b971  boost::asio::detail::scheduler::run()
(pid=raylet)     @     0x55e9b3c8c9a2  boost::asio::io_context::run()
(pid=raylet)     @     0x55e9b35affde  main
(pid=raylet)     @     0x7fc82aa21b97  __libc_start_main
(pid=raylet)     @     0x55e9b35c6bb1  (unknown)
(pid=1525) E1026 09:57:38.073302  1525  1577 core_worker.cc:693] Raylet failed. Shutting down.
(pid=1524) E1026 09:57:38.079627  1524  1589 core_worker.cc:693] Raylet failed. Shutting down.
(pid=1526) E1026 09:57:38.086880  1526  1599 core_worker.cc:693] Raylet failed. Shutting down.
(pid=1528) E1026 09:57:38.109609  1528  1621 core_worker.cc:693] Raylet failed. Shutting down.
(pid=1527) E1026 09:57:38.111768  1527  1627 core_worker.cc:693] Raylet failed. Shutting down.
(pid=1529) E1026 09:57:38.146478  1529  1641 core_worker.cc:693] Raylet failed. Shutting down.
```

**Comment by rkooo567** [comment]
cc @ashione

**Comment by ashione** [comment]
@chaokunyang Is that failure in xlang?

**Comment by ashione** [comment]
@Litchilitchy Could you run it on python3.6 again?

**Comment by chaokunyang** [comment]
@Litchilitchy Does your machine have java installed? Seems `services.py` didn't detect java envirionment, so `StreamingContext` can't create java actor for streaming job build and execution

**Comment by Litchilitchy** [comment]
> @Litchilitchy Could you run it on python3.6 again?

Sorry for mistake.. I ran it on Python 3.6 not Python3.8, edited the title.

**Comment by Litchilitchy** [comment]
> @Litchilitchy Does your machine have java installed? Seems `services.py` didn't detect java envirionment, so `StreamingContext` can't create java actor for streaming job build and execution

I set environment variable `JAVA_HOME` to `path/to/jdk1.8.0_201` the error is still the same

**Comment by chaokunyang** [comment]
@Litchilitchy Which ray version are you using? I need to try it on my machine to locate what's going arong

**Comment by Litchilitchy** [comment]
> @Litchilitchy Which ray version are you using? I need to try it on my machine to locate what's going arong

I am using ray 1.0.0. With PyCharm virtual env python 3.6.

**Comment by chaokunyang** [comment]
After tested on my machine, I found following error by `grep -nr "Error" /tmp/ray/session_latest/logs/`:
```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at io.ray.api.id.JobId.fromInt(JobId.java:47)
        at io.ray.runtime.gcs.GcsClient.nextJobId(GcsClient.java:180)
        at io.ray.runtime.RayNativeRuntime.start(RayNativeRuntime.java:141)
        at io.ray.runtime.DefaultRayRuntimeFactory.createRayRuntime(DefaultRayRuntimeFactory.java:38)
        at io.ray.api.Ray.init(Ray.java:42)
        at io.ray.api.Ray.init(Ray.java:28)
        at io.ray.runtime.runner.worker.DefaultWorker.main(DefaultWorker.java:16)
```
Seems `ray_dist.jar` packaged in the ray wheel is compiled with java11 instead of java8, so using java8 will have get this error.
After deassemble `JobId.class` , it does invoke a method in java11 `// Method java/nio/ByteBuffer.flip:()Ljava/nio/ByteBuffer;` instead of ` // Method java/nio/ByteBuffer.flip:()Ljava/nio/Buffer;`.

**Comment by chaokunyang** [comment]
In ray1.0.0, jar is compiles with jdk11. We've already fixed it in master. If you just want to try out ray streaming, can you upgrade java to java11 or use ray in master branch?

**Comment by chaokunyang** [comment]
And ensure java is in your path. You can test it with `which java`

**Comment by Litchilitchy** [comment]
> In ray1.0.0, jar is compiles with jdk11. We've already fixed it in master. If you just want to try out ray streaming, can you upgrade java to java11 or use ray in master branch?

I upgraded ray to `1.1.0-dev` and the error is the same.

I would try upgrade java next

**Comment by Litchilitchy** [comment]
> And ensure java is in your path. You can test it with `which java`

```
(venv) litchy@Litchy-PC:~/pro/ray-test$ which java
/home/litchy/jdk-11.0.9/bin/java
```
I checked above in terminal, java version is 11
```
(venv) litchy@Litchy-PC:~/pro/ray-test$ java -version
java version "11.0.9" 2020-10-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)
```
The error is still the same -. -

**Comment by chaokunyang** [comment]
I tested it in a linux machine and came across the same problem. It's an existing bug about packing jars into ray wheel. If the jars is not packaged into the wheel, ray will take ray java not installed. I'll try to fix it in #9896. Hope this will be fixed soon.

**Comment by Litchilitchy** [comment]
@chaokunyang So is it a issue related to ray streaming only?

**Comment by chaokunyang** [comment]
@Litchilitchy Actually it's a ray java related issue, not ray streaming related.

**Comment by chaokunyang** [comment]
Close it since #9896 is merged
