### ISSUE TITLE
[tune] [rllib] Tune trials slowing down and reporting incorrect time

### ISSUE THREAD

**Issue by roireshef** [ray-project/ray#12352]
### What is the problem?
I'm running Tune for hyperparameter-search with single-node trials that should last 200M steps each, and which are running simultaneously. My Ray cluster is a private cluster setup. It seems like all of the trials start with ~500 steps/sec rate, and after two to three hours they all start slowing down dramatically. 

Since they all start at the same time (+-1min), I expected Tune to show similar time passed since initiation for all of them (at the summary table it prints occasionally), but the time varies greatly between trials. 

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.7.2 (I'm pretty sure it reproduced in 1.0.1 as well)
Docker 19.03.11
PyTorch 1.5.1
Ubuntu 16.04 / SUSE Linux Enterprise Server 12 SP4

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
I'm running a FLOW-based environment code with confidential logic I can't publish. I'm attaching logs instead. 

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by roireshef** [comment]
_tensorboard_ charts show sampling rate gradually slows down at some point (shows all trials at that same experiment)
![slowed_down_training_num_steps](https://user-images.githubusercontent.com/28055761/100107186-0f227d00-2e72-11eb-88c6-3eba6f6a5253.png)

I'm attaching the _top_ outputs for some node in the cluster (sumo is external process spawned by the environment - it's a traffic simulator the environment's code is interacting with). See how the memory consumption of the RLlib worker went up for processes that exist for more than few hours, while the new (possibly recovered) process has lower memory consumption.
![slowing_down_training](https://user-images.githubusercontent.com/28055761/100107132-ff0a9d80-2e71-11eb-86f6-44296d8ba0b2.png)

Finally, I'm also attaching the _raylet_ logs at that same machine. 

I'm currently debugging under the assumption this is a memory issue, but:
1. I've seen in another issue that @rkooo567 suggested using lru-evict flag, but I fail to apply it to _ray start_ - is it supported in 0.7.2? Also, AFAIK this is a workaround but it's better to find the root cause and fix it. So I wonder how can this be done. Is there any best practice or tool for that?
2. It might be worth printing warnings to the console if memory is exhausted, so detection will be immediate.

**Comment by roireshef** [comment]
@ericl , @richardliaw - I think I have an interesting insights about that issue. I ran two experiments with everything configured exactly the same (both hardware/software), just that one experiment (will be referenced as "stress_test") were given enough nodes to run all trials simultaneously (48 nodes x 32 cores) while the other one (will be referenced as "debug") was given only 10 nodes (but experiment still has 48 trials).

Now, see how trials accumulate steps - the number of steps sampled/trained is shown in next charts for trials from both exepriments - the _debug_ trials have a steady bandwidth, providing linear steps accumulated over time, while the _stress_test_ ones are flattening out over time (their steps per time rate is gradually decreasing):
![debug_vs_stress_test](https://user-images.githubusercontent.com/28055761/100203810-be5f6280-2f0b-11eb-9b97-7296f41f7a21.png)

The only difference between the two is the amount of nodes in the cluster that Tune has to manage simultaneously. The linear lines (_debug_ trials) have occasional drops in them due to crashes and recoveries I'm aware of, and are fixed in my newer environment's code, so please ignore them. 

Another interesting finding is when running _top_ on two nodes (from the different experiments), the one that belongs to _stress_test_ shows ~2GB memory used for all Ray worker processes with quite a lot of them on 0% CPU utilization, whereas _debug_ node's processes have stabilized on ~1GB or ~1.5GB (depending on num_envs_per_worker, which is tested for 3 and 5, respectively) with all processes frequently utilizing CPU well.

**Comment by richardliaw** [comment]
@roireshef do you have output logs from the tune trial? I'm wondering if this is some artifact of checkpointing.

FYI, we don't have long-term support for older versions like 0.7.2

**Comment by roireshef** [comment]
> @roireshef do you have output logs from the tune trial? I'm wondering if this is some artifact of checkpointing.
Can you use the logs in https://github.com/ray-project/ray/issues/12352#issuecomment-733010241 ?

> FYI, we don't have long-term support for older versions like 0.7.2
I understand. I tried migrating from 0.7.2 to several versions (0.8.6, 0.8.7, 1.0.1, 1.1.0), each one had at least one issue that prevented me from migrating successfully. I've been waiting for those to be fixed for some time, but had to continue my actual research. I will be trying to again in about a month from today. That said, I'm pretty sure this specific issue reproduces on newer versions as well. I've recently provided @ericl with reproduction instructions in https://github.com/ray-project/ray/issues/11239#issuecomment-730356995 - seems like my environment is heavier and more memory-demanding than the other ones often used, although here specifically it seems like the the correlation with the number of nodes used by Tune points to a Ray issue rather than the environment implementation.

**Comment by roireshef** [comment]
Hi @richardliaw,

> @roireshef do you have output logs from the tune trial? I'm wondering if this is some artifact of checkpointing.

Can you use the logs in https://github.com/ray-project/ray/issues/12352#issuecomment-733010241 ?

> FYI, we don't have long-term support for older versions like 0.7.2

I understand. I tried migrating from 0.7.2 to several versions (0.8.6, 0.8.7, 1.0.1, 1.1.0), each one had at least one issue that prevented me from migrating successfully. I've been waiting for those to be fixed for some time, but had to continue my actual research. I will be trying to again in about a month from today. That said, I'm pretty sure this specific issue reproduces on newer versions as well. I've recently provided @ericl with reproduction instructions in https://github.com/ray-project/ray/issues/11239#issuecomment-730356995 - seems like my environment is heavier and more memory-demanding than the other ones often used, although here specifically it seems like the the correlation with the number of nodes used by Tune points to a Ray issue rather than the environment implementation.

**Comment by richardliaw** [comment]
> I'm pretty sure it isn't related to checkpointing because while I've set checkpoint to happen every 50 iterations,

I'm referring to an internal Tune checkpointing mechanism. Unfortunately, these logs posted do not capture stdout/stderr of the main python process. Can you please provide stdout/stderr of the python process? If you plan to rerun this, it'd be great to set `ray.init(logging_level="DEBUG")` too.

**Comment by ericl** [comment]
This kind of reminds me of https://github.com/ray-project/ray/issues/4211, though that issue should be solved. It does sound to me like some problem in the Tune event loop and not Ray though.

**Comment by ericl** [comment]
@richardliaw running a similar workload on 50 nodes, I see warnings like this:

2020-11-28 03:12:20,616 WARNING util.py:143 -- The `on_step_begin` operation took 0.8207757472991943 seconds to complete, which may be a performance bottleneck.
2020-11-28 03:12:22,304 WARNING util.py:143 -- The `on_step_begin` operation took 0.8349165916442871 seconds to complete, which may be a performance bottleneck.
2020-11-28 03:12:23,944 WARNING util.py:143 -- The `on_step_begin` operation took 0.805654764175415 seconds to complete, which may be a performance bottleneck.

@roireshef I think it's the large number of concurrent trials is causing Tune to become backlogged processing trial results. One way of fixing this is to increase the reporting period of the trials. In rllib you can set `min_iter_time_s: 30` to report results once per 30 seconds per trial. Can you try this out to see if it helps?

**Comment by roireshef** [comment]
@ericl I'll do that soon and report back, thanks.

**Comment by roireshef** [comment]
> @roireshef do you have output logs from the tune trial? I'm wondering if this is some artifact of checkpointing.
> 
> FYI, we don't have long-term support for older versions like 0.7.2

@richardliaw you actually touched a very frustrating point here. All I was doing for the past month was trying to find a stable Ray version among the newer versions available. I've been blocked for about a month now with my actual work. Nothing is working for me.

**Comment by roireshef** [comment]
![Screenshot from 2020-11-30 21-11-26](https://user-images.githubusercontent.com/28055761/100656285-1d323b00-3355-11eb-86ab-8338c2f94dfc.png)

Yes, it's clear. The 36 nodes experiment just stops making any progress after less than a full hour of training.

@richardliaw, attached:
1. Console outputs from main python process [main_cleaned.tar.gz](https://github.com/ray-project/ray/files/5618403/main_cleaned.tar.gz)
2. Temp logs from some machine across the clusters [logs.tar.gz](https://github.com/ray-project/ray/files/5618405/logs.tar.gz)

**Comment by roireshef** [comment]
@ericl , @richardliaw - Whatever machine I was connecting to and trying to pull the temporary logs out of it, I ended up with the same files. I was under the impression each node stores its own temporary logs. Is it the case where all nodes are communicating temporary logs between one another? @ericl is this why you said it's a O(n^2) thing? Can this be avoided in any way?

**Comment by richardliaw** [comment]
Taking a look!

**Comment by richardliaw** [comment]
@roireshef how did you generate the plot in https://github.com/ray-project/ray/issues/12352#issuecomment-736008751 ? Are they at all related to the logs show in the Console Output from main python process?

In the logs, I'm seeing that every process is making progress and incrementing the "timesteps_total" value. If you look closely, *every trial* at training_iteration = 30 has passed 1e7 timesteps.

What am I missing?

Also, for `/tmp/ray/session_latest`, for me what is most useful is just (raylet, gcs_server) logs on the head node.

**Comment by roireshef** [comment]
> @roireshef how did you generate the plot in [#12352 (comment)](https://github.com/ray-project/ray/issues/12352#issuecomment-736008751) ? Are they at all related to the logs show in the Console Output from main python process?

Yes, the chart at that comment is produced by Tensorboard, overlaying the 36-nodes experiment **with another 3-nodes experiment** for a baseline (the consistent linear progress is made by the 3 expriments in the 3-node cluster).

> In the logs, I'm seeing that every process is making progress and incrementing the "timesteps_total" value. If you look closely, _every trial_ at training_iteration = 30 has passed 1e7 timesteps.
> 
> What am I missing?

@richardliaw - That's very strange. Where excatly do you see 1e7 timesteps? (although 1e7 is also a bad number, it should have been in the scale of 4e7-5e7 timesteps at that point, after more than 24h of training). Are you sure we are looking at the same files? (the ones in https://github.com/ray-project/ray/issues/12352#issuecomment-736008751 

The _main_cleaned.tar.gz_ files is ending with the following lines:
  timers:
    apply_grad_throughput: 264323.924
    apply_grad_time_ms: 3.842
    grad_wait_time_ms: 1.624
    update_time_ms: 1.171
  timestamp: 1606764482
  timesteps_since_restore: 0
  timesteps_total: **1926095**  <-------  see that
  training_iteration: 65
  trial_id: e9458_00023

and the last Tune summary table clearly shows 4000-5000 [sec] in the _total time (s)_ column (although 24h passed from start of experiment, see the date-time reported in some lines, and compare first summary table to last one in that file) and the timesteps column has values ranging in 1e6-2e6...

**Comment by roireshef** [comment]
I guess this is pending https://github.com/ray-project/ray/issues/12360 now...

**Comment by richardliaw** [comment]
Ah, I meant 1e6, sorry! Let me take a look again later.

**Comment by edoakes** [comment]
Hey @roireshef I see the issue you linked is resolved now, can we close this one?

**Comment by roireshef** [comment]
I just ran larger scale experiments few hours ago, I'll report the results tomorrow. So far it looks good.

**Comment by roireshef** [comment]
I'm closing this one, although I feel that this doesn't scale the way I expected, but I'll have to do some more tests and see if this is worth re-opening. Thanks for your help!

**Comment by roireshef** [comment]
This issue isn't resolved, but rather minimized to some degree - previously I was experiencing the slowdowns when scheduling 4 or more trials (each one assigned to a full and single node in the cluster, 32 cores) after 5-6 hours of training. Now it seems like that for 4-8 nodes the slowdowns are minimized to the point they aren't a real issue anymore (although they still exist to some lower degree), but the slowdowns when scheduling 20-40 nodes are definitely there, and pretty much making Tune impractical for hyperparameter-tuning at that scale.

I'm attaching some charts for evidence. Please let me know if you need anything else for debugging.

**Comment by roireshef** [comment]
![Screenshot from 2021-01-02 13-40-55](https://user-images.githubusercontent.com/28055761/103456612-5e28c100-4d00-11eb-954c-8c19c2deed38.png)

![Screenshot from 2021-01-02 13-43-12](https://user-images.githubusercontent.com/28055761/103456616-7d275300-4d00-11eb-9b27-fc567403c956.png)

**Comment by roireshef** [comment]
@ericl - if you need anything from my end (logs, etc.) please LMK. 
Otherwise, I would like to terminate those trials to free the resources assigned to them.

And thanks again!

**Comment by ericl** [comment]
@richardliaw is this fixed now?

**Comment by richardliaw** [comment]
I was planning to leave this open until @sven1977 merges placement groups support for RLlib.

**Comment by roireshef** [comment]
@

> I was planning to leave this open until @sven1977 merges placement groups support for RLlib.

Any plans for when will it happen? It will be much appreciated if we could run RLlib/Tune at scale.

**Comment by roireshef** [comment]
@sven1977 @ericl @richardliaw ?

**Comment by ericl** [comment]
Placement groups are now on by default in the latest release. Should this be closed?

**Comment by roireshef** [comment]
@ericl - is latest release well benchmarked with respect to this issue? Were you able to spawn few 10s of trials with a single Tune call and maintain consistent bandwidth throughout a day or two of training?

**Comment by richardliaw** [comment]
This should be addressed; just created a new issue to track remaining work item.
