### ISSUE TITLE
[k8s] Number of tasks is not being scaled out

### ISSUE THREAD

**Issue by mbehrendt** [ray-project/ray#14402]
### What is the problem?
Ray version 1.2, k8s 18.6 and 19.x, Ubuntu 18.04.

### Reproduction (REQUIRED)
this is in the context of https://github.com/ray-project/ray/issues/14400

when i invoke a task many times in parallel, often times there is no provisioning of additional task instances although there is enough free capacity available.

To reproduce, just setup a k8s cluster as described in the issue referenced above. Then run this code on Ray and watch with `kubctl -n ray get pods` how the number of pods behaves. in general, i've seen very inconsistent behavior across multiple runs - in many cases, the number of pods wasn't scaled at all.

see this thread for further background information: https://discuss.ray.io/t/min-workers-doesnt-seem-to-be-honored/1002

``` import ray
import time
import datetime
import os
import subprocess


ray.init(address='<point to ray on k8s cluster',  _redis_password='insert your own value')

@ray.remote(num_cpus=1)
def f(i):
    time.sleep(30)
    print("index: "  + str(i))


futures = [f.remote(i) for i in range(200)]

print(ray.get(futures)) # [0, 1, 4, 9]
```

@richardliaw ^^

**Comment by rkooo567** [comment]
Hey @wuisawesome maybe the same issue we saw yesterday?

**Comment by wuisawesome** [comment]
Interesting.

@mbehrendt just want to get a better understanding of the issue. Does it look like the problem is that ray isn't using up all the resources on the existing nodes in the cluster? Or do you expect Ray to add _more_ nodes and it's not? 

It may help to share the results of `ray.cluster_resources()` and `ray.available_resources()` while the tasks are running.

**Comment by mbehrendt** [comment]
@wuisawesome based on what i'm seeing in the logs, ray removes the worker nodes again right after startup b/c it identifies it as 'outdated'. As mentioned in the root issue, this only seems to be happening with a larger number of nodes.

For example,, when i set `min_workers` (in the `exampe-full.yaml`you're providing on github, everything seems to be fine (i set the cpu value to 6000m, and 27000Mi as mem -- with 27 8x32 nodes being in the k8s cluster). When I run the 2 functions you referenced above, I'm getting this as output:
``` 2021-02-28 13:01:51,377 INFO worker.py:665 -- Connecting to existing Ray cluster at address: 172.17.61.71:6379
, cluster resources: {'object_store_memory': 1111.0, 'memory': 3775.0, 'node:172.17.61.71': 1.0, 'CPU': 61.0, 'foo': 10.0, 'node:172.17.17.136': 1.0, 'bar': 20.0, 'node:172.17.63.7': 1.0, 'node:172.17.48.135': 1.0, 'node:172.17.38.200': 1.0, 'node:172.17.15.135': 1.0, 'node:172.17.22.70': 1.0, 'node:172.17.35.135': 1.0, 'node:172.17.33.9': 1.0, 'node:172.17.61.72': 1.0, 'node:172.17.34.6': 1.0}
, available resources: {'foo': 10.0, 'node:172.17.33.9': 1.0, 'CPU': 61.0, 'object_store_memory': 1111.0, 'bar': 20.0, 'memory': 3775.0, 'node:172.17.61.72': 1.0, 'node:172.17.63.7': 1.0, 'node:172.17.48.135': 1.0, 'node:172.17.15.135': 1.0, 'node:172.17.22.70': 1.0, 'node:172.17.38.200': 1.0, 'node:172.17.35.135': 1.0, 'node:172.17.61.71': 1.0, 'node:172.17.34.6': 1.0, 'node:172.17.17.136': 1.0}```

If i only changed the min_workers to something a bit higher (e.g. 23), and also raise the `max_workers` value, I'm getting this as output

```
, cluster resources: {'object_store_memory': 1.0, 'CPU': 1.0, 'node:172.17.35.197': 1.0, 'memory': 5.0}
, available resources: {'CPU': 1.0, 'object_store_memory': 1.0, 'memory': 5.0, 'node:172.17.35.197': 1.0}
```

also, as mentioned above i'm seeing this in the logs -- which leads me to believe it initially had all nodes added, but then something caused them to be recognized as being 'outdated':
```
(autoscaler +6s) Removing 21 nodes of type worker_node (outdated).
```

**Comment by AmeerHajAli** [comment]
@mbehrendt , We are actively working on this. We expect this to be resolved by March 26 latest.

**Comment by mbehrendt** [comment]
excellent -- thx so much @AmeerHajAli , really appreciate it

**Comment by DmitriGekhtman** [comment]
> (autoscaler +6s) Removing 21 nodes of type worker_node (outdated).

Thanks for this detail. I'm 95% sure this is a concurrency issue stemming from getting and setting of pods' metadata.labels field.
("node tags" in Ray autoscaler language)

**Comment by DmitriGekhtman** [comment]
Fixed by https://github.com/ray-project/ray/pull/14773 .
@mbehrendt 
will let you know when the nightly image with the fix gets built.

After the image with fix is built --
If using `ray up` to launch with many Ray pods, the Ray head pod should get at least 1Gi memory request+limit .

We'll go ahead and update the cluster launching example configs to have a 1Gi limit..

Thanks again for reporting these issues!

**Comment by DmitriGekhtman** [comment]
An image with the fix has been built!

**Comment by AmeerHajAli** [comment]
@mbehrendt , did we fix your issues? Can you try using the nightly ray version and test if this works for you?

**Comment by mbehrendt** [comment]
@AmeerHajAli unfortunately it seems like the issue i've been seeing is not fixed yet (assuming i didn't make any mistake, which is not unlikely).

In a scenario where there are lots of pending tasks, for instance, scale-out doesn't seem to be happening, pls see the logs i sent you for details.

**Comment by DmitriGekhtman** [comment]
It seems the nightly image once again contains a commit not in master, which once again does not contain scaling fix.
Hopefully this PR is merged soon:
https://github.com/ray-project/ray/pull/14798

In the meantime, please use `rayproject/ray:cd89f0` as the ray head node image.

**Comment by mbehrendt** [comment]
great -- thank you. Switching from `nightly` to this image tag fixed the issue -- the system now behaves as expected.

**Comment by AmeerHajAli** [comment]
Awesome!
Thanks for checking on this!

**Comment by DmitriGekhtman** [comment]
Nightly images should be consistent now, thanks @ijrsvt !
