### ISSUE TITLE
[Core] ref count safety issue when task argument is nested in the return value.

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#17553]
sometimes OBOD gets lookups for objects that the ref counter thinks is out of scope, and responds with error. This causes ObjectNotFound to get raised to the user, crashing the problem:
```
[2021-08-02 18:38:01,396 D 18578 19138] reference_count.cc:500: Calling on_delete for object e2362ccb840337beffffffffffffffffffffffff0100000001000000
[2021-08-02 18:38:01,396 D 18578 19138] core_worker.cc:2626: Object e2362ccb840337beffffffffffffffffffffffff0100000001000000 is deleted. Unpinning the object.
[2021-08-02 18:38:01,396 D 18578 19138] reference_count.cc:483: Deleting Reference to object e2362ccb840337beffffffffffffffffffffffff0100000001000000
[2021-08-02 18:38:01,396 D 18578 19138] reference_count.cc:486: Releasing lineage for object e2362ccb840337beffffffffffffffffffffffff0100000001000000
[2021-08-02 18:38:01,396 D 18578 19138] task_manager.cc:411: Plasma object e2362ccb840337beffffffffffffffffffffffff0100000001000000 out of scope
[2021-08-02 18:38:01,396 D 18578 19138] task_manager.cc:413: Task e2362ccb840337beffffffffffffffffffffffff01000000 has e2362ccb840337beffffffffffffffffffffffff0100000001000000 in scope
[2021-08-02 18:38:01,396 D 18578 19138] task_manager.cc:416: Task e2362ccb840337beffffffffffffffffffffffff01000000 now has 0 plasma returns in scope
[2021-08-02 18:38:01,718 D 18578 19138] reference_count.cc:979: Tried to remove an object location for an object e2362ccb840337beffffffffffffffffffffffff0100000001000000 that doesn't exist in the reference table. It can happen if the object is already evicted.
[2021-08-02 18:38:02,406 D 18578 19138] reference_count.cc:1168: Tried to register a location subscriber for an object e2362ccb840337beffffffffffffffffffffffff0100000001000000 that doesn't exist in the reference table. The object has probably already been freed.
[2021-08-02 18:38:02,407 D 18578 19138] reference_count.cc:1168: Tried to register a location subscriber for an object e2362ccb840337beffffffffffffffffffffffff0100000001000000 that doesn't exist in the reference table. The object has probably already been freed.
```

repro cluster: https://beta.anyscale.com/o/anyscale-internal/projects/prj_Rztp4a5rBZCDvG6vtLZDgpX8/?tab=session-list

```
import time
import numpy as np
import torch
import ray
import argparse
paths = [
    f's3://shuffling-data-loader-benchmarks/data/input_data_{i}.parquet.snappy' for i in range(0, 25)
]
def create_parser():
    parser = argparse.ArgumentParser(description="Eric Example")
    parser.add_argument("--address")
    parser.add_argument(
        "--batch-size",
        type=int,
        default=250000,
        metavar="N",
        help="input batch size for training (default: 64)")
    parser.add_argument("--num-workers", type=int, default=4)
    return parser
def create_torch_iterator(split, batch_size, rank=None):
    print(f"Creating Torch shuffling dataset for worker {rank} with "
          f"{batch_size} batch size.")
    numpy_to_torch_dtype = {
        np.bool: torch.bool,
        np.uint8: torch.uint8,
        np.int8: torch.int8,
        np.int16: torch.int16,
        np.int32: torch.int32,
        np.int64: torch.int64,
        np.float16: torch.float16,
        np.float32: torch.float32,
        np.float64: torch.float64,
        np.complex64: torch.complex64,
        np.complex128: torch.complex128
    }
    DATA_SPEC = {
        "embeddings_name0": (0, 2385, np.int64),
        "embeddings_name1": (0, 201, np.int64),
        "embeddings_name2": (0, 201, np.int64),
        "embeddings_name3": (0, 6, np.int64),
        "embeddings_name4": (0, 19, np.int64),
        "embeddings_name5": (0, 1441, np.int64),
        "embeddings_name6": (0, 201, np.int64),
        "embeddings_name7": (0, 22, np.int64),
        "embeddings_name8": (0, 156, np.int64),
        "embeddings_name9": (0, 1216, np.int64),
        "embeddings_name10": (0, 9216, np.int64),
        "embeddings_name11": (0, 88999, np.int64),
        "embeddings_name12": (0, 941792, np.int64),
        "embeddings_name13": (0, 9405, np.int64),
        "embeddings_name14": (0, 83332, np.int64),
        "embeddings_name15": (0, 828767, np.int64),
        "embeddings_name16": (0, 945195, np.int64),
        "one_hot0": (0, 3, np.int64),
        "one_hot1": (0, 50, np.int64),
        "labels": (0, 1, np.float64),
    }
    feature_columns = list(DATA_SPEC.keys())
    feature_types = [
        numpy_to_torch_dtype[dtype] for _, _, dtype in DATA_SPEC.values()
    ]
    label_column = feature_columns.pop()
    label_type = feature_types.pop()
    torch_iterator = split.to_torch(
         label_column=label_column,
         feature_columns=feature_columns,
         label_column_dtype=label_type,
         feature_column_dtypes=feature_types,
         batch_size=batch_size,
         # prefetch_blocks: int = 0,
         # drop_last: bool = False
    )
    return torch_iterator
def create_dataset(filenames):
    pipeline = ray.data.read_parquet(list(filenames))\
        .repeat().random_shuffle()
    return pipeline
if __name__ == '__main__':
    parser = create_parser()
    args = parser.parse_args()
    print("Connecting to Ray cluster...")
    ray.init(address=args.address)
    pipeline = create_dataset(paths)
    splits = pipeline.split(args.num_workers)
    @ray.remote
    def consume(split, rank=None, batch_size=None):
        torch_iterator = create_torch_iterator(split, batch_size=batch_size, rank=rank)
        for i, (x, y) in enumerate(torch_iterator):
            time.sleep(1)
            if i % 10 == 0:
                print(i)
        return
    tasks = [
        consume.remote(split, rank=idx, batch_size=args.batch_size)
        for idx, split in enumerate(splits)
    ]
    ray.get(tasks)
```

**Comment by scv119** [comment]
@richardliaw can you grant me permission to this session?  https://beta.anyscale.com/o/anyscale-internal/projects/prj_Rztp4a5rBZCDvG6vtLZDgpX8/?tab=session-list thanks!

**Comment by richardliaw** [comment]
done, thanks for looking into this!

**Comment by scv119** [comment]
https://gist.github.com/scv119/6741fb95e1fd1af4a428bfa059cc4029 here is a repro I got. Looks like an under reference counting in OBOD. still looking.

**Comment by scv119** [comment]
Very likely this is the same bug as #17719

**Comment by scv119** [comment]
Finally there is an easy repro:

```
import ray
import numpy as np
import time

ray.init()

class Nested:
  def __init__(self, blocks):
    self._blocks = blocks

@ray.remote
def echo(fn):
    return fn()

@ray.remote
def create_nested():
  refs = [ray.put(np.random.random(1024 * 1024)) for _ in range(10)]
  return Nested(refs)


@ray.remote
def test():
  ref = create_nested.remote()
  result1 = ray.get(ref)
  del ref
  result = echo.remote(lambda: result1)
  del result1

  time.sleep(10)
  block = ray.get(result)._blocks[0]
  print(ray.get(block))


ray.get(test.remote())
```

**Comment by ericl** [comment]
Disabling RAY_max_direct_call_object_size as suggested here https://github.com/ray-project/ray/issues/17719#issuecomment-896351436 doesn't seem to fix this case:

```
eric@anyscale-laptop:~/Desktop$ python repro.py
2021-08-11 13:45:33,615	INFO services.py:1264 -- View the Ray dashboard at http://127.0.0.1:8265
Traceback (most recent call last):
  File "repro.py", line 34, in <module>
    ray.get(test.remote())
  File "/home/eric/Desktop/ray/python/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/eric/Desktop/ray/python/ray/worker.py", line 1621, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::test() (pid=671364, ip=192.168.1.67)
  File "repro.py", line 31, in test
    print(ray.get(block))
ray.exceptions.ObjectLostError: Object 93a66f5f4d0e2328ffffffffffffffffffffffff0100000002000000 is lost due to node failure.
(pid=671364) 2021-08-11 13:45:44,788	WARNING worker.py:1619 -- Local object store memory usage:
(pid=671364) 
(pid=671364) (global lru) capacity: 9109582233
(pid=671364) (global lru) used: 0%
(pid=671364) (global lru) num objects: 0
(pid=671364) (global lru) num evictions: 0
(pid=671364) (global lru) bytes evicted: 0
(pid=671364) 
eric@anyscale-laptop:~/Desktop$ RAY_max_direct_call_object_size=0 python repro.py
2021-08-11 13:45:50,653	INFO services.py:1264 -- View the Ray dashboard at http://127.0.0.1:8265
Traceback (most recent call last):
  File "repro.py", line 34, in <module>
    ray.get(test.remote())
  File "/home/eric/Desktop/ray/python/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/eric/Desktop/ray/python/ray/worker.py", line 1621, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::test() (pid=671759, ip=192.168.1.67)
  File "repro.py", line 31, in test
    print(ray.get(block))
ray.exceptions.ObjectLostError: Object 93a66f5f4d0e2328ffffffffffffffffffffffff0100000002000000 is lost due to node failure.
(pid=671759) 2021-08-11 13:46:01,768	WARNING worker.py:1619 -- Local object store memory usage:
(pid=671759) 
(pid=671759) (global lru) capacity: 9111425433
(pid=671759) (global lru) used: 0%
(pid=671759) (global lru) num objects: 0
(pid=671759) (global lru) num evictions: 0
(pid=671759) (global lru) bytes evicted: 0
(pid=671759) 
```

**Comment by scv119** [comment]
yup. there is an edge case current distributed ref counting didn't handle properly. A fix I'm currently working on is like following:

1. when task returns it returns all the object/nested object refs; currently only inlined nested object refs are returned
.2 when the caller received the returned rpc, we can identify those nested object need a reference bump, either in TaskManager or in ReferenceCounter

**Comment by damdaepark** [comment]
Is this fixed now?
