### ISSUE TITLE
[sgd] Pytorch example fails

### ISSUE THREAD

**Issue by worldveil** [ray-project/ray#18443]
### What is the problem?

```bash
% python --version
Python 3.7.7
% pip freeze | grep ray
ray==1.6.0
```

Mac OS X

### Reproduction (REQUIRED)

```
# ray_train.py
import time 

import ray
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import numpy as np

from ray.util.sgd.torch import TorchTrainer, TrainingOperator

BATCH_SIZE = 8
NUM_DATALOADER_WORKERS = 2
NUM_RAY_WORKERS = 4

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

starttime = time.time()

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = torch.flatten(x, 1)  # flatten all dimensions except batch
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

def model_creator(config):
    return Net()

def cifar_creator(config):
    transform = transforms.Compose(
        [transforms.ToTensor(),
        transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])
    
    # training
    trainset = torchvision.datasets.CIFAR10(
        root='./data', train=True, download=True, transform=transform)
    trainloader = torch.utils.data.DataLoader(
        trainset, batch_size=config["batch_size"],
        shuffle=True, num_workers=config["num_dataloader_workers"])

    # testing
    testset = torchvision.datasets.CIFAR10(
        root='./data', train=False, download=True, transform=transform)
    testloader = torch.utils.data.DataLoader(
        testset, batch_size=config["batch_size"],
        shuffle=False, num_workers=config["num_dataloader_workers"])
    return trainloader, testloader

def optimizer_creator(model, config):
    """Returns an optimizer (or multiple)"""
    return torch.optim.SGD(
        model.parameters(), lr=config["lr"], momentum=config["momentum"])

CustomTrainingOperator = TrainingOperator.from_creators(
    model_creator=model_creator, # A function that returns a nn.Module
    optimizer_creator=optimizer_creator, # A function that returns an optimizer
    data_creator=cifar_creator, # A function that returns dataloaders
    loss_creator=nn.CrossEntropyLoss  # A loss function
)

ray.init(ignore_reinit_error=True)

trainer = TorchTrainer(
    training_operator_cls=CustomTrainingOperator,
    config={"lr": 0.001, # used in optimizer_creator
            "batch_size": BATCH_SIZE, # used in data_creator
            "momentum": 0.9,
            "num_dataloader_workers": NUM_DATALOADER_WORKERS,
           },
    num_workers=NUM_RAY_WORKERS,  # amount of parallelism
    use_gpu=torch.cuda.is_available(),
    use_tqdm=True)

stats = trainer.train()
print(trainer.validate())

torch.save(trainer.state_dict(), "checkpoint.pt")
trainer.shutdown()
print("success!")
```

```
# requirements.txt
anyscale
ray
torch
torchvision
matplotlib
jupyter
pandas
tqdm
````

### Reproduction steps (python 3.7.7) -- error occurs
```
conda create -n entrypoint_pytorch_original python=3.7.7 -y
conda activate entrypoint_pytorch_original
pip install -r requirements.txt
rm -rf ./data
rm cifar_net.pth checkpoint.pt
python ray_train.py
```

Error (1)
```
Traceback (most recent call last):
  File "ray_train.py", line 78, in <module>
    ray.init(ignore_reinit_error=True)
  File "/Users/will/opt/anaconda3/envs/entrypoint_pytorch_original/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/Users/will/opt/anaconda3/envs/entrypoint_pytorch_original/lib/python3.7/site-packages/ray/worker.py", line 896, in init
    ray_params=ray_params)
  File "/Users/will/opt/anaconda3/envs/entrypoint_pytorch_original/lib/python3.7/site-packages/ray/node.py", line 251, in __init__
    redis_client.hset("session_dir", "value", self._session_dir)
  File "/Users/will/opt/anaconda3/envs/entrypoint_pytorch_original/lib/python3.7/site-packages/redis/client.py", line 3050, in hset
    return self.execute_command('HSET', name, *items)
  File "/Users/will/opt/anaconda3/envs/entrypoint_pytorch_original/lib/python3.7/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/Users/will/opt/anaconda3/envs/entrypoint_pytorch_original/lib/python3.7/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/Users/will/opt/anaconda3/envs/entrypoint_pytorch_original/lib/python3.7/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
zsh: terminated  python ray_train.py
```

Error (2)
```
<hangs indefinitely>
```

I've tried this a couple times. 

### Reproduction steps (python 3.8.10) -- error occurs, but script finishes

Identical, except for this conda env setup. 

```bash
conda create -n entrypoint_pytorch_retry python=3.8.10 -y
conda activate entrypoint_pytorch_retry
pip install -r requirements.txt
rm -rf ./data
rm cifar_net.pth checkpoint.pt
python ray_train.py. # hits error (1)
```

Error (1), but still hits "success!" print at end

```
(pid=69898) *** SIGSEGV received at time=1631130160 ***
(pid=69898) PC: @        0x10c2b8711  (unknown)  c10d::TCPStoreMasterDaemon::queryFds()
(pid=69898)     @        0x101f38a64  (unknown)  absl::lts_20210324::WriteFailureInfo()
(pid=69898)     @        0x101f387cb  (unknown)  absl::lts_20210324::AbslFailureSignalHandler()
(pid=69898)     @     0x7fff6b43f5fd  (unknown)  _sigtramp
(pid=69898)     @        0x10c2b8800  (unknown)  c10d::TCPStoreMasterDaemon::queryFds()
(pid=69898)     @        0x10c2b8266  (unknown)  c10d::TCPStoreMasterDaemon::run()
(pid=69898)     @        0x10c2bddee  (unknown)  std::__1::__thread_proxy<>()
(pid=69898)     @     0x7fff6b44b109  (unknown)  _pthread_start
(pid=69898)     @     0x7fff6b446b8b  (unknown)  thread_start
2021-09-08 12:42:41,173 WARNING worker_group.py:410 -- Failed to shutdown gracefully.
2021-09-08 12:42:41,174 WARNING worker.py:1215 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff49eeed2b256ddfd73a3c1a8201000000 Worker ID: 16d50f4f94b9ff0c11ed63927bff8ad946c12dc22de3da6fa082c6ec Node ID: c56c49719bb87effd24ae4e4a4bf2ef2d51f636de7beee9576fc6be6 Worker IP address: 192.168.86.96 Worker port: 54362 Worker PID: 69898
success!  # still succeeds....
```

**Comment by matthewdeng** [comment]
Thanks for the clean reproduction steps! I was able to reproduce the errors, sort of.

(1) I ran into a separate redis issue when calling `ray.init()` for the first time. This is unrelated to SGD altogether, I created a ticket to track this here: https://github.com/ray-project/ray/issues/18454

(2) Just to confirm, which step of the script did your job hang at? In my case, I ran `py-spy dump` and saw that it is hanging at `trainer.shutdown()`.  I tried running this with the latest wheels and got the same error. It is a bit strange that this is happening in Python 3.7 but not Python 3.8, but I can look deeper into this.
```
Thread 0x10F6F5E00 (idle): "MainThread"
    get_objects (ray/worker.py:348)
    get (ray/worker.py:1613)
    wrapper (ray/_private/client_mode_hook.py:82)
    _terminate_remote_workers (ray/util/sgd/torch/worker_group.py:403)
    shutdown (ray/util/sgd/torch/worker_group.py:417)
    shutdown (ray/util/sgd/torch/torch_trainer.py:600)
    <module> (ray_train.py:96)
```

**Comment by worldveil** [comment]
I saw a different redis error: `redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value zsh: terminated  python ray_train.py` -- do you see that one as well?

@matthewdeng to answer your question, it hangs on `trainer.shutdown()`

**Comment by amogkam** [comment]
Error 2 should be resolved by https://github.com/ray-project/ray/pull/18473. Error 1 is an issue with Ray Core itself, not with Ray SGD.

**Comment by matthewdeng** [comment]
> I saw a different redis error: `redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value zsh: terminated python ray_train.py` -- do you see that one as well?

No, I ran into an issue that occurs 3 lines earlier in `Node.__init__()`:
https://github.com/ray-project/ray/blob/f0555f88d6d3d1912a68405565098a775af655f4/python/ray/node.py#L248
So it never hit the line that triggers your error:
https://github.com/ray-project/ray/blob/f0555f88d6d3d1912a68405565098a775af655f4/python/ray/node.py#L251

Oddly enough we're experiencing different errors bubbled up from Redis, both of which go away on the second run.

**Comment by worldveil** [comment]
Is this a redis issue, or a Ray issue?

**Comment by worldveil** [comment]
I still see this error every time I run a ray script on my laptop:

```
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
zsh: terminated  python ray_train.py
```

**Comment by amogkam** [comment]
Is this resolved @matthewdeng @worldveil?

**Comment by amogkam** [comment]
Closing this as the Ray SGD related failure has been fixed, and the redis issue is being tracked in #20166
