### ISSUE TITLE
[Ray HA] Head node support active/standby feature

### ISSUE THREAD

**Issue by larrylian** [ray-project/ray#22164]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

The following K8s deployment is an example. Now the components redis and gcs server that persist core data are deployed on the head node. If the head node fails, the entire ray cluster will be unavailable. 
For high availability. Now plan to change the deployment architecture and add head node active and standby features. This feature adds redundancy in the form of an Active/Standby Head Node pair to remove this otherwise head node or gcs server single point of failure. 

1、Strip out the redis in the head node and start it as a separate pod.
2、Start two head nodes。start cmd like: ray start --head --enable-high-availability --external-redis-addresses=xxx
3、The startup script(ray start cmd) in the head node will connect to redis to compete for the master.
4、 Only the nodes that successfully compete for the master will start the gcs_server/dashboard process after normal execution.
5、The standby node will always be stuck in the master competition process. Only after waiting for the original master node to fail, and then this node becomes the master node, will it go on.
6、 Then the gcs client periodically obtains the value of GcsServerAddress, and if it finds that the gcs address has changed, it will automatically reconnect.

![image](https://user-images.githubusercontent.com/11072802/152736908-31ccc043-70c6-4aaa-9a71-719352bcf2b6.png)

Note:
1、
If switch to the "gcs bootstrap" feature. Then I need to make some modifications to this feature, and need to introduce third-party components such as zookeeper or others. It is used for multi-head node election and dynamic discovery of addresses by gcs client.

2、This new "lite-head" mode is the premise of my head-standby ha feature。Need to strip redis and raylet from head node。

Welcome everyone to communicate with each other.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by wilsonwang371** [comment]
Just saw this. Btw, the design might need to be revised a little bit. Since a recent switch from "redis bootstrap" to  "gcs bootstrap".

**Comment by wilsonwang371** [comment]
Do you guys think adding a new "lite-head" mode for head node can be a first step feature?
https://github.com/ray-project/ray/issues/22744

**Comment by larrylian** [comment]
> Btw, the design might need to be revised a little bit. Since a recent switch from "redis bootstrap" to "gcs bootstrap".
yes。 If switch to the "gcs bootstrap" feature. Then I need to make some modifications to this feature, and need to introduce third-party components such as zookeeper or others. It is used for multi-head node election and dynamic discovery of addresses by gcs client.

> Do you guys think adding a new "lite-head" mode for head node can be a first step feature? #22744
yes.  This new "lite-head" mode is the premise of my head-standby ha feature， I totally approve of your "lite-head" mode feature。 We have implemented this "lite-head" mode inside ant group。

**Comment by wilsonwang371** [comment]
> @wilsonwang371
> 
> > Btw, the design might need to be revised a little bit. Since a recent switch from "redis bootstrap" to "gcs bootstrap".
> 
> yes。 If switch to the "gcs bootstrap" feature. Then I need to make some modifications to this feature, and need to introduce third-party components such as zookeeper or others. It is used for multi-head node election and dynamic discovery of addresses by gcs client.
> 
> > Do you guys think adding a new "lite-head" mode for head node can be a first step feature? #22744
> 
> yes. This new "lite-head" mode is the premise of my head-standby ha feature， I totally approve of your "lite-head" mode feature。 We have implemented this "lite-head" mode inside ant group。

Regarding the ray-client server local raylet socket connections, what is your opinion on this?

**Comment by tsaoyu** [comment]
How many external dependencies would requires for the 'lite head' mode?
Have you considered any HA services provided by cloud vendors?

**Comment by hongbo-miao** [comment]
I originally asked at https://stackoverflow.com/q/79468588/2000548

I found enabling Global Control Service (GCS) fault tolerance only makes Ray job history stays after head node after restarting.

However, I found if a job running and Ray head node dies, after it auto restarts, the job still shows "running", but it is not in healthy state any more and eventually will become "failed".

So today this is still no solution that I am aware of to make Ray head node high availability without interrupting the jobs that are running. 😔
