### ISSUE TITLE
[Core] better support for Dataset prefetching

### ISSUE THREAD

**Issue by scv119** [ray-project/ray#23983]
### What happened + What you expected to happen

Today in Ray Dataset we relies on `ray.wait(fetch_local=True)` to implement prefetching. However, as we benchmarked in https://github.com/ray-project/ray/pull/23952 it's not working as expected.

~We need investigate and fix ray.wait, as this has been used by a lot of existing libraries. We should clearly define its behavior, and fix them accordingly. More specifically, we should make sure `ray.wait(fetch_local=True)` fetch the objects locally, (or as good as the actor based solution).~

We need to figure out the solution, potentially:
1. we can enhance `ray.wait(fetch_local=True)` to match the expected behavior of prefetching.
2. we can introduce a new API to fit into dataset prefetching's behavior.

### Versions / Dependencies

latest 

### Reproduction script

please see description in https://github.com/ray-project/ray/pull/23952 

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by suquark** [comment]
progress: I am still investigating it, should have some results today or early next week

**Comment by suquark** [comment]
Actually I think this doc example already give us the solution for prefetching: https://docs.ray.io/en/latest/ray-core/actors/async_api.html#objectrefs-as-concurrent-futures-futures

Or more concretely:

```python
def prefetch(refs):
    for fut in concurrent.futures.as_completed([ref.future() for ref in refs]):
        yield fut.result()
```

**Comment by suquark** [comment]
@scv119 based on our discussion, it seems the `ray.wait` semantics is actually correct, and we may not want to change it. Should we close this issue?

**Comment by hora-anyscale** [comment]
Per Triage Sync: This is already fixed.

**Comment by clarkzinzow** [comment]
@hora-anyscale @scv119 @stephanie-wang How is this already fixed?

**Comment by scv119** [comment]
My understanding is that we concluded that ray.wait semantics is correct and we should have a separate API for data prefetching

**Comment by clarkzinzow** [comment]
I think the conclusion was that the `ray.wait()` semantics are **not** what the user expects, but we fundamentally need a stateful API and wedging that into the existing `ray.wait()` API would be complex.

We can close this issue if we're going to leave the `ray.wait()` API alone (and possibly deprecate it eventually), but can we make sure that we still have a tracking issue for the prefetching use case? I don't want that to get lost.

**Comment by ericl** [comment]
Closing this in favor of https://github.com/ray-project/ray/issues/30375
