### ISSUE TITLE
[RFC][Core] Add `get_actor(actor_id)` API to simplify applications.

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#28407]
### Description

Passing actor handles across workers may make actors unmanageable in frameworks on the top of Ray.

### Use case

For the use case1, currently, most applications should save the checkpoints of serialized actor handles for some failure recovery reasons, which may cause errors if users haven't loaded the actor handles from serialized bytes carefully. For example, users often make actor handles as a field of another type deeply. If they use custom serializers which don't invoke `CoreWorker.DeserializeActorHandle()`, a crash should be raised.

For the use case2, frameworks on the top of Ray always need handle the actors of other jobs. In anther words, frameworks may exchange the information including actor id. THAT MEANS actorA may receive the actor id of actorB, and actorA may call actorB for some reasons, which also lead crashes if we haven't used actorB in actorA before.

### Proposal
Adding the API `get_actor(actor_id)` should address the above issues.

About the implementation, we could just add a RPC to get the actor handle bytes from GCS. I believe there is no side effect because we only borrow the actor handle and doesn't affect any behavior on distributed reference counting.

@scv119 @rkooo567 @kfstorm for more voices.

**Comment by simon-mo** [comment]
Maybe we can consider an internal/experimental API? cc @iycheng as well.

**Comment by scv119** [comment]
can you use named actor to serve the same purpose？can you be more specific about the suggested API?

**Comment by jovany-wang** [comment]
> can you use named actor to serve the same purpose？

No, it couldn't be addressed in named actor. As we all know, Ray is a very flexible system, so we built many frameworks or tool jobs on top of that. Image that we have a long serving job which serves for other Ray jobs, if we use the names to manage all actors from the other jobs, stuff should be unmaintainable.

For an instance, we have a long serving job which monitors the workloads of nodes, once a node is overload, it will notify the related jobs that the actors on that node will be evicted soon. At the high level design, users should not be aware of the actor locations, so we notify the actor ids to user jobs.
![image](https://user-images.githubusercontent.com/19473861/191702719-0846b880-3d99-469c-b662-09e48a26b97e.png)



> can you be more specific about the suggested API? I.e. how to use the ‘get_actor’ to solve the problem you described?

1. `get_actor(actor_id)` this API should return the actor handle by the given actor id.
2. once this API get done, if the users could do a graceful actor migration by theirselves, like:
```python
class ServeMaster:
    
    @override
    def __on_actor_migration__(self, actor_id):
        target_actor = ray.get_actor(actor_id)
        # ingress flows forward to another actor.
        target_actor.kill()

```

**Comment by scv119** [comment]
> No, it couldn't be addressed in named actor. 

Why? Looks named actor is exactly designed to solve your problem; where the only inconvenience is that an actor doesn't have a name by default. If that's the case, is one option to extend the named actor API to auto generate a name to an actor?

**Comment by jovany-wang** [comment]
> Why? Looks named actor is exactly designed to solve your problem; where the only inconvenience is that an actor doesn't have a name by default. If that's the case, is one option to extend the named actor API to auto generate a name to an actor?

We couldn't use named actor to address it because the application consists of a framework(like ray serve) and an application on the top of that framework. for the users of the framework, we have no idea to restrict them to only use actors within a given name.

The actor ids are fetched in a Master component in the framework, like we could watch the actor state changed in ServeMaster by fetch all actors every interval.

**Comment by jovany-wang** [comment]
@scv119 More thoughts?

**Comment by wumuzi520** [comment]
@scv119 We look forward to your more input. BTW, we still have a strong demand for this interface internally.

**Comment by wumuzi520** [comment]
The proposed api like this:
```
# actor.py
class ActorHandle:
    def get_actor_id() -> string:
          pass

# worker.py
def get_actor(name: str, actor_id: str, namespace: str = None) -> ActorHandle:
    pass
```

**Comment by rkooo567** [comment]
The use case seems to be pretty tailored to the internal use cases (e.g., long running job that notifies other jobs when node is overloaded -> this is not a common scenario from Ray users). But I think this won't be a huge API change anyway, so I vote for doing this to unblock them. Should we start with experimental APIs? (e.g., get_actor(_actor_id=None))
