### ISSUE TITLE
Core: hang during atexit shutdown handler

### ISSUE THREAD

**Issue by pconrad-insitro** [ray-project/ray#29431]
### What happened + What you expected to happen

I was running a badly configured job, which needs lots more memory than was requested. As a result, it caused a lot of OOMs. Ray continued, however, and managed to run much of the computation. However, when calling `ray.shutdown`, either manually, or via the `atexit` handler, it can hang.

Here's the `py-spy dump` output for the atexit handler case. It's in the middle of shutdown due to a raised exception:

```
Thread 0x7F2BA8E31740 (idle): "MainThread"
    wait (threading.py:312)
    __del__ (grpc/_channel.py:1247)
    close (ray/_private/gcs_pubsub.py:284)
    disconnect (ray/_private/worker.py:2119)
    shutdown (ray/_private/worker.py:1581)
    wrapper (ray/_private/client_mode_hook.py:105)
Thread 0x7F2BA4361700 (idle): "fsspecIO"
    select (selectors.py:469)
    _run_once (asyncio/base_events.py:1869)
    run_forever (asyncio/base_events.py:601)
    run (threading.py:917)
    _bootstrap_inner (threading.py:980)
    _bootstrap (threading.py:937)
Thread 0x7F2640FF9700 (idle): "ray_print_logs"
    wait (threading.py:312)
    __del__ (grpc/_channel.py:1247)
    _bootstrap_inner (threading.py:982)
    _bootstrap (threading.py:937)
Thread 0x7F2640FF9700 (active): "ray_print_logs"
Thread 0x7F2641FFB700 (active)
```

The last line looks truncated, but that's what py-spy output. The `fsspecIO` thread is ours. 

I verified with gdb that it's stuck on a futex wait. One of the easiest ways for that to happen is if another thread died while holding the lock - I suspect that's what is happening here. Unfortunately I don't have symbols available, so I can't verify which thread it was. 

There are a number of error messages in the logs. Samples:

```
	WARNING worker.py:1829 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 24278de1850c89287383c45f74759caf300ce58c01000000 Worker ID: 021ed352fca3e8c9c961da1bfe00103d148228e2645842277992f638 Node ID: a0e250b3e0d3f52a2a5dd1c77c7d8969a7375eb915e39e8d03208007 Worker IP address: <snip> Worker port: 10009 Worker PID: 232 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
```

```
Traceback (most recent call last):
--
File "lib/python3.9/site-packages/ray/_private/log_monitor.py", line 344, in check_log_files_and_publish_updates
next_line = file_info.file_handle.readline()
OSError: [Errno 12] Cannot allocate memory
During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
 File "lib/python3.9/site-packages/ray/_private/log_monitor.py", line 520, in <module>
 log_monitor.run()
 File "lib/python3.9/site-packages/ray/_private/log_monitor.py", line 436, in run
 anything_published = self.check_log_files_and_publish_updates()
File "lib/python3.9/site-packages/ray/_private/log_monitor.py", line 383, in check_log_files_and_publish_updates
f"position: {file_info.file_info.file_handle.tell()} "
 AttributeError: 'LogFileInfo' object has no attribute 'file_info'
 Exception in thread ray_print_logs:
 Traceback (most recent call last):
 File "lib/python3.9/threading.py", line 980, in _bootstrap_inner

```

```
 WARNING worker.py:1829 -- The log monitor on node <snip> failed with the following error:
-- | --
 Traceback (most recent call last):
File "lib/python3.9/site-packages/ray/_private/log_monitor.py", line 520, in <module>
 log_monitor.run()
 File "lib/python3.9/site-packages/ray/_private/log_monitor.py", line 435, in run
 self.open_closed_files()
 File "lib/python3.9/site-packages/ray/_private/log_monitor.py", line 279, in open_closed_files
 raise e
 File "lib/python3.9/site-packages/ray/_private/log_monitor.py", line 270, in open_closed_files
 file_size = os.path.getsize(file_info.filename)
 File "lib/python3.9/genericpath.py", line 50, in getsize
 return os.stat(filename).st_size
CopyOSError: [Errno 12] Cannot allocate memory: '/tmp/ray/session_2022-10-17_19-16-33_539744_12/logs/worker-4a6efb52918f22015042db9e21a1e02fcb53b406e2a39176f2248bb3-01000000-118.out' | OSError: [Errno 12] Cannot allocate memory: '/tmp/ray/session_2022-10-17_19-16-33_539744_12/logs/worker-4a6efb52918f22015042db9e21a1e02fcb53b406e2a39176f2248bb3-01000000-118.out'
```

```
Exception in thread ray_listen_error_messages:
--
 Traceback (most recent call last):
 File "lib/python3.9/threading.py", line 980, in _bootstrap_inner
 Running Segmentation: 0%\| \| 10/2700 [00:22<1:40:24, 2.24s/it]
self.run()
 File "lib/python3.9/threading.py", line 917, in run
 self._target(*self._args, **self._kwargs)
 File "lib/python3.9/site-packages/ray/_private/worker.py", line 1814, in listen_error_messages
 _, error_data = worker.gcs_error_subscriber.poll()
 File "lib/python3.9/site-packages/ray/_private/gcs_pubsub.py", line 317, in poll
 self._poll_locked(timeout=timeout)
 File "lib/python3.9/site-packages/ray/_private/gcs_pubsub.py", line 240, in _poll_locked
 fut = self._stub.GcsSubscriberPoll.future(
 File "lib/python3.9/site-packages/grpc/_channel.py", line 972, in future
 call = self._managed_call(
 File "lib/python3.9/site-packages/grpc/_channel.py", line 1306, in create
 _run_channel_spin_thread(state)
 File "lib/python3.9/site-packages/grpc/_channel.py", line 1270, in _run_channel_spin_thread
 channel_spin_thread.start()
 File "src/python/grpcio/grpc/_cython/_cygrpc/fork_posix.pyx.pxi", line 117, in grpc._cython.cygrpc.ForkManagedThread.start
 File "lib/python3.9/threading.py", line 899, in start
 _start_new_thread(self._bootstrap, ())
 RuntimeError: can't start new thread
```

Other instances also show workers getting OOM killed. My best guess is that one of these log threads died in the host application, leaving it in a broken state.

This is a multi-node ray cluster, although I'm unclear if that matters. On the head node, we start the ray cluster with the CLI, then the main python process on the head node joins itself with `ray.init(address='localhost')` (we need to customize the port, which I can't do from the python API `init`). This error is from that main python process.

I'm not sure what a fix will be, exactly, since getting a clean shutdown after errors is hard. However, it probably needs to be a little more defensive here, since this code will still run during an exception exit. I've been digging into this because having the cluster fail to tear down can be expensive.

I can prevent this hang in a very hacky way by preventing part of the shutdown handler from running:
```
from ray._private.worker import global_worker

# Mutate their internal state to avoid actually performing steps of the
# worker `disconnect` routine (same module) that appear able to hang
# upon node shutdown.
global_worker.node = None
```
This is hardly a good solution, but is useful to understand.

### Versions / Dependencies

Linux, ray v2.0.0, python 3.9, grpc v1.46.3

### Reproduction script

I can get it to trip somewhat reliably, but only a large code base I can't share. I don't understand it well enough to reproduce simply, but per above, it may be possible to make a simpler reproduction by killing threads.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by rkooo567** [comment]
cc @cadedaniel

**Comment by cadedaniel** [comment]
Downgrading to P1 given that there's a hacky workaround.

@pconrad-insitro how consistent is this issue? Does it happen every time or more stochastic?

**Comment by cadedaniel** [comment]
I think this behavior is currently unavoidable, since some additional memory is required to shut down cleanly. We have an improved OOM killer in development which I think will make this happen much less. Assigning to @clarence-wu , feel free to close/deprioritize if it'll be fixed by the new OOM killer.

**Comment by pconrad-insitro** [comment]
Thanks all for the triaging, and @cadedaniel for the insight about the better OOM implementation. This particular instance was nearly deterministic, but I don't know that it's easy to recreate. I would readily admit that this task was very badly behaved and wildly misconfigured, I'm only noting it because ray is clearly trying to be careful about this kind of error handling. I tried some simple matrix allocations to create OOMs and it caught and failed the jobs as intended.

I think it makes sense for ray to try as hard as possible to shut down the cluster, and the atexit handler is a good place to do this. But it looked to me like the actual resources that caused problems here might be internal to the process. If so, and we're just about to shut down the process, perhaps it doesn't matter, and it would be better to avoid risking the hang? Would it make sense to update the atexit handler not to run this code if it's in the process of unwinding? Or, I'm not sure if it could be jailed with a timeout to avoid the hang? In a manner of speaking, I suppose this would require deciding that my workaround has the right effect. I don't know enough about this system to decide in either direction.

**Comment by rkooo567** [comment]
actually @pconrad-insitro when you change the exception catching here to `except Exception`, does the hang still happen? 

https://github.com/ray-project/ray/blob/398300252611547acc4d47b2f645e580e828965b/python/ray/_private/worker.py#L1839

Based on your theory, my guess is the grpc is dead with mutex hold. My expectation is upon this sort of thread failure, the mutex should be released, but idk the grpc internals... If this is reproducible I am curious if this will fix the issue.

**Comment by rkooo567** [comment]
cc @pconrad-insitro for the follow up!

**Comment by pconrad-insitro** [comment]
@rkooo567  - thanks for the suggestion. Unfortunately, this doesn't seem to help.

I changed it to these two lines, so we'd also get some output if it happened:
```
except Exception:
            logger.info("caught all exceptions")
```

It doesn't look like it got called and the hang still occurred as before. I suspect the thread is getting OOM killed while holding the lock, otherwise as you suggest, we would expect grpc to release the mutex as exceptions unwind.

I don't think I've seen the recommendation to configure the OS OOM killer. Is there a link you can share?

**Comment by rkooo567** [comment]
I think this is usually configured by default.

https://www.oracle.com/technical-resources/articles/it-infrastructure/dev-oom-killer.html -> for OS

from ray 2.1, (will be released in a week or so), you can also try https://docs.ray.io/en/master/ray-core/scheduling/ray-oom-prevention.html

**Comment by pconrad-insitro** [comment]
Thanks @rkooo567  - I browsed the doc for the new feature, I agree it seems very useful and should provide a lot of protection. Thanks for exploring this with me. At this point, I think it's reasonable to close this as both "not directly fixable" and "soon to be mitigated".

**Comment by rkooo567** [comment]
Thanks for the quick response and engagement! Please let me know if you have any other issue :) !
