### ISSUE TITLE
Core: at least one of the input arguments could not be computed

### ISSUE THREAD

**Issue by bje-** [ray-project/ray#33715]
### What happened + What you expected to happen

I expected the attached code to work. Instead, I see:

```
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RaySystemError: System error: Can't get attribute 'Individual' on <module 'deap.creator' from '/home/bje/.local/lib/python3.10/site-packages/deap/creator.py'>
```

### Versions / Dependencies

Python 3.10, Ray 2.3.1, DEAP 1.3.3

### Reproduction script

```
import ray
from deap import base, creator

ray.init()
creator.create("FitnessMax", base.Fitness, weights=(1.0,))
creator.create("Individual", list, fitness=creator.FitnessMax)

def parmap(mapfn, lst):
    futures = [mapfn.remote(x) for x in lst]
    return ray.get(futures)

@ray.remote
def evalOneMax(individual):
    return sum(individual)

ind1 = creator.Individual(range(0, 5))
ind2 = creator.Individual(range(10, 15))
ind3 = creator.Individual(range(20, 25))

parmap(evalOneMax, [ind1, ind2, ind3])
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by rkooo567** [comment]
This seems like the error from your module?

**Comment by rkooo567** [comment]
Hmm I think it is because `creator.create("Individual", list, fitness=creator.FitnessMax)` is configured per-proc, and when the same Individual is accessed from other process (started by ray), it is not configured. 

If I initiate the 

```
    creator.create("FitnessMax", base.Fitness, weights=(1.0,))
    creator.create("Individual", list, fitness=creator.FitnessMax)
```
to all workers using `ray._private.worker.global_worker.run_function_on_all_workers(c)`, it is fixed. (however, `run_function_on_all_workers` is a API we will deprecate, and we will give you an alternative when we have one. You can use this API for now). 

```
import ray
from deap import base, creator

ray.init()

def c(worker_info):
    creator.create("FitnessMax", base.Fitness, weights=(1.0,))
    creator.create("Individual", list, fitness=creator.FitnessMax)

ray._private.worker.global_worker.run_function_on_all_workers(c)

def parmap(mapfn, lst):
    futures = [mapfn.remote(x) for x in lst]
    return ray.get(futures)

@ray.remote
def evalOneMax(individual):
    return sum(individual)

ind1 = creator.Individual(range(0, 5))
ind2 = creator.Individual(range(10, 15))
ind3 = creator.Individual(range(20, 25))

parmap(evalOneMax, [ind1, ind2, ind3])
```

**Comment by bje-** [comment]
That's exactly the answer I was looking for. Thank you!

**Comment by bje-** [comment]
Hmm, maybe not after all. This still doesn't work for me. I tried to debug it, but then found that even the below doesn't work as I expect:

```
import ray
ray.init(num_cpus=4)

def c(worker_info):
    print(worker_info)

ray._private.worker.global_worker.run_function_on_all_workers(c)
print("Done")
```

I see only one `worker_info` printed. Huh?

```
 /home/bje/Downloads/example.py:7: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
This function is deprecated and will be removed by Ray 2.4. Please use Runtime Environments https://docs.ray.io/en/releases-2.3.1/ray-core/handling-dependencies.html to manage dependencies in workers.
  ray._private.worker.global_worker.run_function_on_all_workers(c)
{'worker': <ray._private.worker.Worker object at 0x7fc1a40912d0>}
Done
```

**Comment by rkooo567** [comment]
I think they are not printed because you didn't submit any task/actor?

**Comment by rkooo567** [comment]
Is it possible to start the cluster with `ray start --head` and try again?

**Comment by bje-** [comment]
I started a cluster with `ray start --head` and the example gave the same result. What should I expect to have happened differently?

**Comment by rkooo567** [comment]
```
import ray
ray.init(num_cpus=4)

def c(worker_info):
    print(worker_info)

ray._private.worker.global_worker.run_function_on_all_workers(c)
print("Done")

@ray.remote
def f():
    pass

ray.get(f.remote())
```

Hmm when I added tasks, it seems to work? You can only get logs streamed to driver from the same job

**Comment by bje-** [comment]
Returning to your full example above, I see:

```
/home/bje/Downloads/example.py:10: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
This function is deprecated and will be removed by Ray 2.4. Please use Runtime Environments https://docs.ray.io/en/releases-2.3.1/ray-core/handling-dependencies.html to manage dependencies in workers.
  ray._private.worker.global_worker.run_function_on_all_workers(c)
Traceback (most recent call last):
  File "/home/bje/Downloads/example.py", line 24, in <module>
    parmap(evalOneMax, [ind1, ind2, ind3])
  File "/home/bje/Downloads/example.py", line 14, in parmap
    return ray.get(futures)
  File "/home/bje/.local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/bje/.local/lib/python3.10/site-packages/ray/_private/worker.py", line 2380, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::evalOneMax() (pid=544879, ip=192.168.1.55)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RaySystemError: System error: Can't get attribute 'Individual' on <module 'deap.creator' from '/home/bje/.local/lib/python3.10/site-packages/deap/creator.py'>
traceback: Traceback (most recent call last):
AttributeError: Can't get attribute 'Individual' on <module 'deap.creator' from '/home/bje/.local/lib/python3.10/site-packages/deap/creator.py'>
(evalOneMax pid=544878) 2023-03-28 16:53:59,226	ERROR serialization.py:371 -- Can't get attribute 'Individual' on <module 'deap.creator' from '/home/bje/.local/lib/python3.10/site-packages/deap/creator.py'>
```

**Comment by rkooo567** [comment]
```
        """This function has been deprecated given the following issues:
            - no guarantee that the function run before the remote function run.
            - pubsub signal might be lost in some failure cases.

        This API will be deleted once we move the working dir init away.
        NO NEW CODE SHOULD USE THIS API.
```

Hmm this is written in the API docstring... maybe the first item `no guarantee that the function run before the remote function run.` is the reason why it doesn't work.


I actually found we have an alternative API https://discuss.ray.io/t/how-can-i-run-a-python-function-in-each-workers-interpreter-as-it-joins/4122/4

Is it possible for you to try this? I think what you need is to create a setup method `c` in our example and pass it to the env var using runtime env

**Comment by rkooo567** [comment]
```
        """This function has been deprecated given the following issues:
            - no guarantee that the function run before the remote function run.
            - pubsub signal might be lost in some failure cases.

        This API will be deleted once we move the working dir init away.
        NO NEW CODE SHOULD USE THIS API.
```

This is the docstring of this method. I found `no guarantee that the function run before the remote function run.` seems to be the root cause of this issue. 

I am trying to propose APIs to improve this experience in the next version. Before that, do you think this is the reasonable workaround for you?

```python3
import ray
from deap import base, creator

ray.init()

def parmap(mapfn, lst):
    futures = [mapfn.remote(x) for x in lst]
    return ray.get(futures)

@ray.remote
def evalOneMax(range):
    creator.create("FitnessMax", base.Fitness, weights=(1.0,))
    creator.create("Individual", list, fitness=creator.FitnessMax)
    return sum(creator.Individual(range))

parmap(evalOneMax, [range(0, 5), range(10, 15), range(20, 25)])
```
?

Also `creator.create("FitnessMax", base.Fitness, weights=(1.0,))` -> is this method okay to be called multiple times?

**Comment by bje-** [comment]
I wish I'd thought of that! DEAP does produce a warning that the type is being re-created, but I think I can make a case to the developers that it's OK to not have the warning. Thanks, this is the best solution so far. :+1:
