### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by kjang96** [ray-project/ray#3413]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.14
- **Ray installed from (source or binary)**: source 
- **Ray version**:  up-to-date w/master
- **Python version**: 3.5.2
- **Exact command to reproduce**: python setup.py develop

### Describe the problem

When I run `python setup.py develop` from a clean version of master, the command fails. I've installed all dependencies for OSX according to https://ray.readthedocs.io/en/latest/installation.html and am running this in a conda env. My initial suspicious is that is an issue with cmake or pyarrow. I tried using versions 3.13.0 and 3.10.1 of cmake. Both failed. 

### Source code / logs

```
-- Running cmake for pyarrow
cmake -DPYTHON_EXECUTABLE=/Users/kathyjang/anaconda/envs/flow/bin/python  -DPYARROW_BUILD_PARQUET=on -DPYARROW_BOOST_USE_SHARED=on -DPYARROW_BUILD_PLASMA=on -DPYARROW_USE_TENSORFLOW=on -DPYARROW_BUNDLE_ARROW_CPP=ON -DCMAKE_BUILD_TYPE=release /Users/kathyjang/research/ray/build/external/arrow/src/arrow_ep/python
[ 38%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/gcs/client.cc.o
-- The C compiler identification is AppleClang 10.0.0.10001145
[ 39%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/gcs/tables.cc.o
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- broken
CMake Error at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/CMakeTestCXXCompiler.cmake:45 (message):
  The C++ compiler

    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/kathyjang/research/ray/build/external/arrow/src/arrow_ep/python/build/temp.macosx-10.6-x86_64-3.5/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_186a4/fast"
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_186a4.dir/build.make CMakeFiles/cmTC_186a4.dir/build
    Building CXX object CMakeFiles/cmTC_186a4.dir/testCXXCompiler.cxx.o
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    '-stdlib=libc++'  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.6   -o CMakeFiles/cmTC_186a4.dir/testCXXCompiler.cxx.o -c /Users/kathyjang/research/ray/build/external/arrow/src/arrow_ep/python/build/temp.macosx-10.6-x86_64-3.5/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
    make[4]: *** [CMakeFiles/cmTC_186a4.dir/testCXXCompiler.cxx.o] Error 1
    make[3]: *** [cmTC_186a4/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:25 (project)


-- Configuring incomplete, errors occurred!
See also "/Users/kathyjang/research/ray/build/external/arrow/src/arrow_ep/python/build/temp.macosx-10.6-x86_64-3.5/CMakeFiles/CMakeOutput.log".
See also "/Users/kathyjang/research/ray/build/external/arrow/src/arrow_ep/python/build/temp.macosx-10.6-x86_64-3.5/CMakeFiles/CMakeError.log".
error: command 'cmake' failed with exit status 1
make[2]: *** [external/pyarrow/src/pyarrow_ext-stamp/pyarrow_ext-configure] Error 1
make[1]: *** [CMakeFiles/pyarrow_ext.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 40%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/gcs/redis_context.cc.o
[ 41%] Linking CXX static library liblocal_scheduler_client.a
[ 41%] Built target local_scheduler_client
[ 41%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/gcs/asio.cc.o
[ 42%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/util/logging.cc.o
[ 43%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/common/client_connection.cc.o
[ 43%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/common/common_protocol.cc.o
[ 44%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/object_manager/object_manager_client_connection.cc.o
[ 45%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/object_manager/connection_pool.cc.o
[ 46%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/object_manager/object_buffer_pool.cc.o
[ 46%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/object_manager/object_store_notification_manager.cc.o
[ 47%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/object_manager/object_directory.cc.o
[ 48%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/object_manager/object_manager.cc.o
[ 49%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/raylet/monitor.cc.o
[ 49%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/raylet/mock_gcs_client.cc.o
[ 50%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/raylet/task.cc.o
[ 51%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/raylet/task_execution_spec.cc.o
[ 52%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/raylet/task_spec.cc.o
[ 52%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/raylet/worker.cc.o
[ 53%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/raylet/worker_pool.cc.o
[ 54%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/raylet/scheduling_resources.cc.o
[ 55%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/raylet/actor_registration.cc.o
[ 55%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/raylet/scheduling_queue.cc.o
[ 56%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/raylet/scheduling_policy.cc.o
[ 57%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/raylet/task_dependency_manager.cc.o
[ 58%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/raylet/reconstruction_policy.cc.o
[ 58%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/raylet/node_manager.cc.o
[ 59%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/raylet/lineage_cache.cc.o
[ 60%] Building CXX object src/ray/CMakeFiles/ray_objlib.dir/raylet/raylet.cc.o
[ 61%] Building C object src/ray/CMakeFiles/ray_objlib.dir/thirdparty/hiredis/async.c.o
[ 61%] Building C object src/ray/CMakeFiles/ray_objlib.dir/thirdparty/hiredis/dict.c.o
[ 62%] Building C object src/ray/CMakeFiles/ray_objlib.dir/thirdparty/hiredis/hiredis.c.o
/Users/kathyjang/research/ray/src/ray/thirdparty/hiredis/dict.c:53:21: warning: unused function
      'dictGenHashFunction' [-Wunused-function]
static unsigned int dictGenHashFunction(const unsigned char *buf, int len) {
                    ^
/Users/kathyjang/research/ray/src/ray/thirdparty/hiredis/dict.c:73:14: warning: unused function
      'dictCreate' [-Wunused-function]
static dict *dictCreate(dictType *type, void *privDataPtr) {
             ^
/Users/kathyjang/research/ray/src/ray/thirdparty/hiredis/dict.c:160:12: warning: unused function
      'dictReplace' [-Wunused-function]
static int dictReplace(dict *ht, void *key, void *val) {
           ^
/Users/kathyjang/research/ray/src/ray/thirdparty/hiredis/dict.c:182:12: warning: unused function
      'dictDelete' [-Wunused-function]
static int dictDelete(dict *ht, const void *key) {
           ^
/Users/kathyjang/research/ray/src/ray/thirdparty/hiredis/dict.c:238:13: warning: unused function
      'dictRelease' [-Wunused-function]
static void dictRelease(dict *ht) {
            ^
/Users/kathyjang/research/ray/src/ray/thirdparty/hiredis/dict.c:258:22: warning: unused function
      'dictGetIterator' [-Wunused-function]
static dictIterator *dictGetIterator(dict *ht) {
                     ^
/Users/kathyjang/research/ray/src/ray/thirdparty/hiredis/dict.c:268:19: warning: unused function
      'dictNext' [-Wunused-function]
static dictEntry *dictNext(dictIterator *iter) {
                  ^
/Users/kathyjang/research/ray/src/ray/thirdparty/hiredis/dict.c:288:13: warning: unused function
      'dictReleaseIterator' [-Wunused-function]
static void dictReleaseIterator(dictIterator *iter) {
            ^
8 warnings generated.
[ 63%] Building C object src/ray/CMakeFiles/ray_objlib.dir/thirdparty/hiredis/net.c.o
[ 63%] Building C object src/ray/CMakeFiles/ray_objlib.dir/thirdparty/hiredis/read.c.o
[ 64%] Building C object src/ray/CMakeFiles/ray_objlib.dir/thirdparty/hiredis/sds.c.o
[ 65%] Building C object src/ray/CMakeFiles/ray_objlib.dir/thirdparty/sha256.c.o
[ 65%] Built target ray_objlib
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 175, in <module>
    license="Apache 2.0")
  File "/Users/kathyjang/anaconda/envs/flow/lib/python3.5/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/Users/kathyjang/anaconda/envs/flow/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/kathyjang/anaconda/envs/flow/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/kathyjang/anaconda/envs/flow/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/kathyjang/anaconda/envs/flow/lib/python3.5/site-packages/setuptools/command/develop.py", line 36, in run
    self.install_for_development()
  File "/Users/kathyjang/anaconda/envs/flow/lib/python3.5/site-packages/setuptools/command/develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "/Users/kathyjang/anaconda/envs/flow/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/kathyjang/anaconda/envs/flow/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 76, in run
    subprocess.check_call(["../build.sh", "-p", sys.executable])
  File "/Users/kathyjang/anaconda/envs/flow/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../build.sh', '-p', '/Users/kathyjang/anaconda/envs/flow/bin/python']' returned non-zero exit status 2
```

**Comment by kjang96** [comment]
Updated: from the history of this file, I reverted to 99bac443751d1fd4998cf1b880e5a31670707700 and this bug is resolved.

**Comment by kjang96** [comment]
@robertnishihara Yes

**Comment by robertnishihara** [comment]
Ok, after some updates, I'm seeing the issue as well

```
        warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
        1 warning generated.
        Linking CXX executable cmTC_0fd14
        /usr/local/Cellar/cmake/3.10.2/bin/cmake -E cmake_link_script CMakeFiles/cmTC_0fd14.dir/link.txt --verbose=1
        /Library/Developer/CommandLineTools/usr/bin/c++    -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.7 -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_0fd14.dir/testCXXCompiler.cxx.o  -o cmTC_0fd14
        clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
        ld: library not found for -lstdc++
        clang: error: linker command failed with exit code 1 (use -v to see invocation)
        make[4]: *** [cmTC_0fd14] Error 1
        make[3]: *** [cmTC_0fd14/fast] Error 2




      CMake will not be able to correctly generate this project.
    Call Stack (most recent call first):
      CMakeLists.txt:25 (project)


    -- Configuring incomplete, errors occurred!
```

Note that I'm using MacOS 10.13.6.

**Comment by eugenevinitsky** [comment]
Is there a fix or a timeline for an attempted fix for this? Just curious; we still have this issue.

**Comment by robertnishihara** [comment]
I think this issue should be gone now that we're building with Bazel.
