### ISSUE TITLE
[RLlib] MultiDiscrete Action Space not supported in Ray 2.7

### ISSUE THREAD

**Issue by alexpalms** [ray-project/ray#39421]
### What happened + What you expected to happen

When Ray RLlib is used on an environment with a `MultiDiscrete` action space it crashes. This bug has already been reported for previous versions (see https://github.com/ray-project/ray/issues/35923, https://github.com/ray-project/ray/pull/36803) but it was supposed to be fixed with the `2.7` release which is still failing.

The script below (that is a tiny modification of [this example of yours](https://github.com/ray-project/ray/blob/master/rllib/examples/nested_action_spaces.py), and thus uses your `NestedSpaceRepeatAfterMeEnv` environment), when run with ray `2.6.3`, fails with the following error: `AttributeError: 'TorchCategorical' object has no attribute 'log_prob'` while when run with the new `2.7.0rc0` fails with: `AttributeError: '<class 'ray.rllib.models.torch.torch_distributions' object has no attribute 'action_space'`

I also tested it with a different environment featuring a `MultiDiscrete` action space, and it fails in a different way, with the error message `AttributeError: '<class 'ray.rllib.models.torch.torch_distributions' object has no attribute 'cats'`

### Versions / Dependencies

Ray 2.7.0rc0

### Reproduction script

```
import argparse
from gymnasium.spaces import Dict, Tuple, Box, Discrete, MultiDiscrete
import os

import ray
from ray import air, tune
from ray.tune.registry import register_env
from ray.rllib.examples.env.nested_space_repeat_after_me_env import (
    NestedSpaceRepeatAfterMeEnv,
)
from ray.rllib.utils.test_utils import check_learning_achieved
from ray.tune.registry import get_trainable_cls

parser = argparse.ArgumentParser()
parser.add_argument(
    "--run", type=str, default="PPO", help="The RLlib-registered algorithm to use."
)
parser.add_argument(
    "--framework",
    choices=["tf", "tf2", "torch"],
    default="torch",
    help="The DL framework specifier.",
)
parser.add_argument("--num-cpus", type=int, default=0)
parser.add_argument(
    "--as-test",
    action="store_true",
    help="Whether this script should be run as a test: --stop-reward must "
    "be achieved within --stop-timesteps AND --stop-iters.",
)
parser.add_argument(
    "--local-mode",
    action="store_true",
    help="Init Ray in local mode for easier debugging.",
)
parser.add_argument(
    "--stop-iters", type=int, default=100, help="Number of iterations to train."
)
parser.add_argument(
    "--stop-timesteps", type=int, default=100000, help="Number of timesteps to train."
)
parser.add_argument(
    "--stop-reward", type=float, default=0.0, help="Reward at which we stop training."
)

if __name__ == "__main__":
    args = parser.parse_args()
    ray.init(num_cpus=args.num_cpus or None, local_mode=args.local_mode)
    register_env(
        "NestedSpaceRepeatAfterMeEnv", lambda c: NestedSpaceRepeatAfterMeEnv(c)
    )

    config = (
        get_trainable_cls(args.run)
        .get_default_config()
        .environment(
            "NestedSpaceRepeatAfterMeEnv",
            env_config={
                "space": Dict(
                    {
                        "a": Tuple(
                            [Dict({"d": Box(-10.0, 10.0, ()), "e": Discrete(2)})]
                        ),
                        "b": Box(-10.0, 10.0, (2,)),
                        "c": MultiDiscrete([3, 3]),
                    }
                ),
            },
        )
        .framework(args.framework)
        .rollouts(num_rollout_workers=0, num_envs_per_worker=20)
        # No history in Env (bandit problem).
        .training(gamma=0.0, lr=0.0005)
        # Use GPUs iff `RLLIB_NUM_GPUS` env var set to > 0.
        .resources(num_gpus=int(os.environ.get("RLLIB_NUM_GPUS", "0")))
    )

    if args.run == "PPO":
        config.training(
            # We don't want high entropy in this Env.
            entropy_coeff=0.00005,
            num_sgd_iter=4,
            vf_loss_coeff=0.01,
        )

    stop = {
        "training_iteration": args.stop_iters,
        "episode_reward_mean": args.stop_reward,
        "timesteps_total": args.stop_timesteps,
    }

    results = tune.Tuner(
        args.run, param_space=config, run_config=air.RunConfig(stop=stop, verbose=1)
    ).fit()

    if args.as_test:
        check_learning_achieved(results, args.stop_reward)

    ray.shutdown()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by alexpalms** [comment]
@ArturNiederfahrenhorst note that I just simplified the snipped even more:
```
import argparse
from gymnasium.spaces import Dict, Tuple, Box, Discrete, MultiDiscrete
import os

import ray
from ray import air, tune
from ray.tune.registry import register_env
from ray.rllib.utils.test_utils import check_learning_achieved
from ray.tune.registry import get_trainable_cls


import gymnasium as gym
from gymnasium.spaces import Box, Dict, Discrete, Tuple
import numpy as np
import tree  # pip install dm_tree

from ray.rllib.utils.spaces.space_utils import flatten_space


class CustomEnv(gym.Env):
    """Env for which policy has to repeat the (possibly complex) observation.

    The action space and observation spaces are always the same and may be
    arbitrarily nested Dict/Tuple Spaces.
    Rewards are given for exactly matching Discrete sub-actions and for being
    as close as possible for Box sub-actions.
    """

    def __init__(self, config):
        self.observation_space = Box(-1.0, 1.0, (2,))
        self.action_space = MultiDiscrete([2,2])
        self.flattened_action_space = flatten_space(self.action_space)
        self.episode_len = 100

    def reset(self, *, seed=None, options=None):
        self.steps = 0
        return self._next_obs(), {}

    def step(self, action):
        self.steps += 1
        action = tree.flatten(action)
        reward = 0.0
        for a, o, space in zip(
            action, self.current_obs_flattened, self.flattened_action_space
        ):
            # Box: -abs(diff).
            if isinstance(space, gym.spaces.Box):
                reward -= np.sum(np.abs(a - o))
            # Discrete: +1.0 if exact match.
            if isinstance(space, gym.spaces.Discrete):
                reward += 1.0 if a == o else 0.0
        done = truncated = self.steps >= self.episode_len
        return self._next_obs(), reward, done, truncated, {}

    def _next_obs(self):
        self.current_obs = self.observation_space.sample()
        self.current_obs_flattened = tree.flatten(self.current_obs)
        return self.current_obs


parser = argparse.ArgumentParser()
parser.add_argument(
    "--run", type=str, default="PPO", help="The RLlib-registered algorithm to use."
)
parser.add_argument(
    "--framework",
    choices=["tf", "tf2", "torch"],
    default="torch",
    help="The DL framework specifier.",
)
parser.add_argument("--num-cpus", type=int, default=0)
parser.add_argument(
    "--as-test",
    action="store_true",
    help="Whether this script should be run as a test: --stop-reward must "
    "be achieved within --stop-timesteps AND --stop-iters.",
)
parser.add_argument(
    "--local-mode",
    action="store_true",
    help="Init Ray in local mode for easier debugging.",
)
parser.add_argument(
    "--stop-iters", type=int, default=100, help="Number of iterations to train."
)
parser.add_argument(
    "--stop-timesteps", type=int, default=100000, help="Number of timesteps to train."
)
parser.add_argument(
    "--stop-reward", type=float, default=0.0, help="Reward at which we stop training."
)

if __name__ == "__main__":
    args = parser.parse_args()
    ray.init(num_cpus=args.num_cpus or None, local_mode=args.local_mode)
    register_env(
        "CustomEnv", lambda c: CustomEnv(c)
    )

    config = (
        get_trainable_cls(args.run)
        .get_default_config()
        .environment("CustomEnv")
        .framework(args.framework)
        .rollouts(num_rollout_workers=0, num_envs_per_worker=20)
        # No history in Env (bandit problem).
        .training(gamma=0.0, lr=0.0005)
        # Use GPUs iff `RLLIB_NUM_GPUS` env var set to > 0.
        .resources(num_gpus=int(os.environ.get("RLLIB_NUM_GPUS", "0")))
    )

    if args.run == "PPO":
        config.training(
            # We don't want high entropy in this Env.
            entropy_coeff=0.00005,
            num_sgd_iter=4,
            vf_loss_coeff=0.01,
        )

    stop = {
        "training_iteration": args.stop_iters,
        "episode_reward_mean": args.stop_reward,
        "timesteps_total": args.stop_timesteps,
    }

    results = tune.Tuner(
        args.run, param_space=config, run_config=air.RunConfig(stop=stop, verbose=1)
    ).fit()

    if args.as_test:
        check_learning_achieved(results, args.stop_reward)

    ray.shutdown()
```

And this reproduces what I have been experiencing with my custom env, so the error `AttributeError: '<class 'ray.rllib.models.torch.torch_distributions' object has no attribute 'cats'`

**Comment by sven1977** [comment]
Actually, this might have been fixed by this PR here:
https://github.com/ray-project/ray/pull/39464

But let me check ...

**Comment by alexpalms** [comment]
@sven1977 thanks for the feedback!

**Comment by alexpalms** [comment]
@sven1977 super cool, thanks for the quick fix! Will this be included in the 2.7 release? Do you already have a release date for it?

**Comment by linshuxi** [comment]
Is the problem solved? I get similar problem in DQN, and the error is: ray.rllib.utils.error.UnsupportedSpaceException: Action space MultiDiscrete([11  5  1  2]) is not supported for DQN.

**Comment by linshuxi** [comment]
@sven1977 There is still some problem in ray2.7, and still cannot use PPO for MultiDiscrete action distributions. And the error information is :
    raise NotImplementedError("No KL(p || q) is implemented for p type {} and q type {}"
NotImplementedError: No KL(p || q) is implemented for p type TorchCategorical and q type TorchCategorical

**Comment by alexpalms** [comment]
@sven1977 @ArturNiederfahrenhorst I just installed the lib and tested the latest script shared in this issue and I sill have the error.

## Steps to replicate
1) `conda create --name new-ray python=3.8`
2) `conda activate new-ray`
3) `pip install -U ray[rllib] torch`
4) `python script.py` where the script is attached below

## Script.py
```
import argparse
from gymnasium.spaces import Dict, Tuple, Box, Discrete, MultiDiscrete
import os

import ray
from ray import air, tune
from ray.tune.registry import register_env
from ray.rllib.utils.test_utils import check_learning_achieved
from ray.tune.registry import get_trainable_cls


import gymnasium as gym
from gymnasium.spaces import Box, Dict, Discrete, Tuple
import numpy as np
import tree  # pip install dm_tree

from ray.rllib.utils.spaces.space_utils import flatten_space


class CustomEnv(gym.Env):
    """Custom env with multi discrete action space

    """

    def __init__(self, config):
        self.observation_space = Box(-1.0, 1.0, (2,))
        self.action_space = MultiDiscrete([2,2])
        self.flattened_action_space = flatten_space(self.action_space)
        self.episode_len = 100

    def reset(self, *, seed=None, options=None):
        self.steps = 0
        return self._next_obs(), {}

    def step(self, action):
        self.steps += 1
        action = tree.flatten(action)
        reward = 0.0
        for a, o, space in zip(
            action, self.current_obs_flattened, self.flattened_action_space
        ):
            # Box: -abs(diff).
            if isinstance(space, gym.spaces.Box):
                reward -= np.sum(np.abs(a - o))
            # Discrete: +1.0 if exact match.
            if isinstance(space, gym.spaces.Discrete):
                reward += 1.0 if a == o else 0.0
        done = truncated = self.steps >= self.episode_len
        return self._next_obs(), reward, done, truncated, {}

    def _next_obs(self):
        self.current_obs = self.observation_space.sample()
        self.current_obs_flattened = tree.flatten(self.current_obs)
        return self.current_obs


parser = argparse.ArgumentParser()
parser.add_argument(
    "--run", type=str, default="PPO", help="The RLlib-registered algorithm to use."
)
parser.add_argument(
    "--framework",
    choices=["tf", "tf2", "torch"],
    default="torch",
    help="The DL framework specifier.",
)
parser.add_argument("--num-cpus", type=int, default=0)
parser.add_argument(
    "--as-test",
    action="store_true",
    help="Whether this script should be run as a test: --stop-reward must "
    "be achieved within --stop-timesteps AND --stop-iters.",
)
parser.add_argument(
    "--local-mode",
    action="store_true",
    help="Init Ray in local mode for easier debugging.",
)
parser.add_argument(
    "--stop-iters", type=int, default=100, help="Number of iterations to train."
)
parser.add_argument(
    "--stop-timesteps", type=int, default=100000, help="Number of timesteps to train."
)
parser.add_argument(
    "--stop-reward", type=float, default=0.0, help="Reward at which we stop training."
)

if __name__ == "__main__":
    args = parser.parse_args()
    ray.init(num_cpus=args.num_cpus or None, local_mode=args.local_mode)
    register_env(
        "CustomEnv", lambda c: CustomEnv(c)
    )

    config = (
        get_trainable_cls(args.run)
        .get_default_config()
        .environment("CustomEnv")
        .framework(args.framework)
        .rollouts(num_rollout_workers=0, num_envs_per_worker=20)
        # No history in Env (bandit problem).
        .training(gamma=0.0, lr=0.0005)
        # Use GPUs iff `RLLIB_NUM_GPUS` env var set to > 0.
        .resources(num_gpus=int(os.environ.get("RLLIB_NUM_GPUS", "0")))
    )

    if args.run == "PPO":
        config.training(
            # We don't want high entropy in this Env.
            entropy_coeff=0.00005,
            num_sgd_iter=4,
            vf_loss_coeff=0.01,
        )

    stop = {
        "training_iteration": args.stop_iters,
        "episode_reward_mean": args.stop_reward,
        "timesteps_total": args.stop_timesteps,
    }

    results = tune.Tuner(
        args.run, param_space=config, run_config=air.RunConfig(stop=stop, verbose=1)
    ).fit()

    if args.as_test:
        check_learning_achieved(results, args.stop_reward)

    ray.shutdown()
```

## Relevant Error Log
```
Traceback (most recent call last):
  File "/home/alexpalms/miniconda3/envs/new-ray/lib/python3.8/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/home/alexpalms/miniconda3/envs/new-ray/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/alexpalms/miniconda3/envs/new-ray/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/alexpalms/miniconda3/envs/new-ray/lib/python3.8/site-packages/ray/_private/worker.py", line 2547, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::PPO.train() (pid=702896, ip=192.168.0.38, actor_id=4759bace2b689d18ce33dc4101000000, repr=PPO)
  File "/home/alexpalms/miniconda3/envs/new-ray/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 400, in train
    raise skipped from exception_cause(skipped)
  File "/home/alexpalms/miniconda3/envs/new-ray/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 397, in train
    result = self.step()
  File "/home/alexpalms/miniconda3/envs/new-ray/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 853, in step
    results, train_iter_ctx = self._run_one_training_iteration()
  File "/home/alexpalms/miniconda3/envs/new-ray/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 2838, in _run_one_training_iteration
    results = self.training_step()
  File "/home/alexpalms/miniconda3/envs/new-ray/lib/python3.8/site-packages/ray/rllib/algorithms/ppo/ppo.py", line 448, in training_step
    train_results = self.learner_group.update(
  File "/home/alexpalms/miniconda3/envs/new-ray/lib/python3.8/site-packages/ray/rllib/core/learner/learner_group.py", line 184, in update
    self._learner.update(
  File "/home/alexpalms/miniconda3/envs/new-ray/lib/python3.8/site-packages/ray/rllib/core/learner/learner.py", line 1304, in update
    ) = self._update(nested_tensor_minibatch)
  File "/home/alexpalms/miniconda3/envs/new-ray/lib/python3.8/site-packages/ray/rllib/core/learner/torch/torch_learner.py", line 365, in _update
    return self._possibly_compiled_update(batch)
  File "/home/alexpalms/miniconda3/envs/new-ray/lib/python3.8/site-packages/ray/rllib/core/learner/torch/torch_learner.py", line 123, in _uncompiled_update
    loss_per_module = self.compute_loss(fwd_out=fwd_out, batch=batch)
  File "/home/alexpalms/miniconda3/envs/new-ray/lib/python3.8/site-packages/ray/rllib/core/learner/learner.py", line 1024, in compute_loss
    loss = self.compute_loss_for_module(
  File "/home/alexpalms/miniconda3/envs/new-ray/lib/python3.8/site-packages/ray/rllib/algorithms/ppo/torch/ppo_torch_learner.py", line 87, in compute_loss_for_module
    action_kl = prev_action_dist.kl(curr_action_dist)
  File "/home/alexpalms/miniconda3/envs/new-ray/lib/python3.8/site-packages/ray/rllib/models/torch/torch_distributions.py", line 327, in kl
    for cat, oth_cat in zip(self._cats, other.cats)
AttributeError: '<class 'ray.rllib.models.torch.torch_distributions' object has no attribute 'cats'
```
## Full Error Log
(attached)
[FullErrorLog.log](https://github.com/ray-project/ray/files/12705302/FullErrorLog.log)

**Comment by nlinc1905** [comment]
@alexpalms I have been having the same issue with Ray 2.7.1.  As a workaround, I have replaced my MultiDiscrete action with a Tuple of Discrete actions.  For example, in your original script:
```
            env_config={
                "space": Dict(
                    {
                        "a": Tuple(
                            [Dict({"d": Box(-10.0, 10.0, ()), "e": Discrete(2)})]
                        ),
                        "b": Box(-10.0, 10.0, (2,)),
                        "c": Tuple([Discrete(3), Discrete(3)]),  # MultiDiscrete([3, 3])),
                    }
                ),
            },
```
Another possible workaround might be to flatten the space with [spaces.utils.flatten_space](https://gymnasium.farama.org/api/spaces/utils/), which will convert MultiDiscrete to a Box.  The catch with this approach is that the sampling from the action space would get distorted, because Boxes are not discrete.

**Comment by heihei-nie** [comment]
> [@sven1977](https://github.com/sven1977) super cool, thanks for the quick fix! Will this be included in the 2.7 release? Do you already have a release date for it?

sir, I met the same problem as yours. So how can we solve it? The problem is AttributeError: '<class 'ray.rllib.models.torch.torch_distributions' object has no attribute 'cats'
