### ISSUE TITLE
[tune] Full /tmp/ folder, ray does not clean up 

### ISSUE THREAD

**Issue by daviddavo** [ray-project/ray#41202]
### What happened + What you expected to happen

My /tmp/ folder is full of folders called `tmp[randomstring]` with the following files:

```
-rw-rw-r--    1 daviddavo daviddavo  101 Nov 16 02:22 checkpoint
-rw-rw-r--    1 daviddavo daviddavo  24M Nov 16 02:22 model.data-00000-of-00001
-rw-rw-r--    1 daviddavo daviddavo  378 Nov 16 02:22 model.index
-rw-rw-r--    1 daviddavo daviddavo 677K Nov 16 02:22 model.meta
```

Most of them are not of the current experiment, but from old experiments. This has been slowly filling up the /tmp/ partition.

### Versions / Dependencies

Ray version: 2.7.1

### Reproduction script

I'm training a TF model, concretely:

https://github.com/recommenders-team/recommenders/blob/main/recommenders/models/deeprec/models/graphrec/lightgcn.py

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by matthewdeng** [comment]
Hey I think this should be addressed in the nightly version of Ray, which includes https://github.com/ray-project/ray/pull/41033

**Comment by daviddavo** [comment]
Oh, I searched in the issues to see if it was reported but I did not notice the pull request. Feel free to close this issue.

**Comment by matthewdeng** [comment]
Sounds good I'll mark this one as closed, please feel free to try out the new version and re-open if you still have any issues. Thanks!

**Comment by ninnghazad** [comment]
This still happens with ray version 2.10.0

Putting something like this at the top of the trainable works, but well ...
`os.system("find /tmp -name keras.model -type f -mmin +360 -delete")`

Can this be re-opened?

**Comment by drukoz** [comment]
> ###
> [Apr 19, 2024](#issuecomment-2066349625)

yes this is still happening on my end as well. i was the original ticket and my tmp folder is being filled to the point where i need to set my tmp folder to a NFS share

**Comment by Liquidmasl** [comment]
I actually have the same issue in linux now, we have a dedicated 4tb nvme just for the ray tmps and it runs full

I think its because we just kill the process that is running ray, so ray may not have time to clean up after itself. 
I do call ray.shutdown() prior of killing the process, but i dont see how i can wait for the cleanup to be done...

**Comment by anyscalesam** [comment]
Tks, I wonder if this regression is poking out again (re-reading this Issue it was supposed to be fixed but before my team w/ Anyscale).

Will follow up next week...

**Comment by anyscalesam** [comment]
Tks, I wonder if this regression is poking out again (re-reading this Issue it was supposed to be fixed but before my team w/ Anyscale).

Will follow up next week...

**Comment by AwesomeLemon** [comment]
Hi @anyscalesam, I'm facing the same issue, could you tell me if there has been any progress?

**Comment by jjyao** [comment]
We currently don't clean up /tmp folders which store logs.

**Comment by Liquidmasl** [comment]
> We currently don't clean up /tmp folders which store logs.

well that actually makes sense!
Can we somehow place logs somewhere else so it is being cleaned up? or can just the non logs be cleaned up?
For now we just call a rm -rv on the folder on container exit.. which works but is a bit.. smelly

**Comment by jjyao** [comment]
Hi @Liquidmasl what are the non-logs that are in the /tmp folders after Ray shuts down?
