### ISSUE TITLE
[RLlib] Action masking example with new API stack error

### ISSUE THREAD

**Issue by ciroaceto** [ray-project/ray#44452]
### What happened + What you expected to happen

The first error occurs during the build method of the RL module:
```
class ActionMaskRLMBase(RLModule):
    def __init__(self, config: RLModuleConfig):
        if not isinstance(config.observation_space, gym.spaces.Dict):
            raise ValueError(
                "This model requires the environment to provide a "
                "gym.spaces.Dict observation space."
            )
```
This happens because the observation space of the module_spec variable (setup method of Algorithm class) only contains the observations and not the action mask, even though the preprocessor api is disabled. I could get around this adding the env and spaces variables to the get_marl_module_spec method (algorithm.py) and some lines to algorithm_config.py as follows:

algorithm.py:742
```
module_spec: MultiAgentRLModuleSpec = self.config.get_marl_module_spec(
                    policy_dict=policy_dict, env=env, spaces=spaces
                )
```
algorithm_config.py:3582
```
if module_spec.observation_space is None:
                if self.action_mask_key == 'action_mask':
                    module_spec.observation_space = env.observation_space
                    module_spec.observation_space['observations'] = spaces[module_id][0]
                else:
                    module_spec.observation_space = policy_spec.observation_space
```
Probably it's not the best solution, but it works. After solving this first issue the training loop starts.

Next, the following error comes up:

`RuntimeError: Tensor.__contains__ only supports Tensor or scalar, but you passed in a <class 'str'>.`

The batch variable of the PPOTorchRLModule only contains 'obs' and no 'action_mask'. Therefore, there is something wrong during the creation of the batch that is removing the 'action_mask' part of the observation space.

### Versions / Dependencies

Ray: 2.10
gymnasium: 0.28.1
torch: 2.2.1
python: 3.10.11
OS: Windows 11

### Reproduction script

```
from gymnasium.spaces import Box, Discrete
from ray.tune.logger import pretty_print
from ray.rllib.algorithms import ppo
from ray.rllib.core.rl_module.rl_module import SingleAgentRLModuleSpec
from ray.rllib.env.single_agent_env_runner import SingleAgentEnvRunner
from ray.rllib.examples.env.action_mask_env import ActionMaskEnv
from ray.rllib.examples.rl_module.action_masking_rlm import TorchActionMaskRLM


rlm_spec = SingleAgentRLModuleSpec(module_class=TorchActionMaskRLM)

config = (
    ppo.PPOConfig()
    .environment(
        ActionMaskEnv,
        env_config={
                "action_space": Discrete(100),
                "observation_space": Box(-1.0, 1.0, (5,)),
            },
    )
    .experimental(
        _enable_new_api_stack=True,
        _disable_preprocessor_api=True,
    )
    .framework("torch")
    .training(model={"uses_new_env_runners": True})
    .rollouts(
        num_rollout_workers = 0,
        env_runner_cls= SingleAgentEnvRunner,
    )
    .rl_module(rl_module_spec=rlm_spec)
    .resources(
        num_learner_workers=0,
        num_gpus_per_learner_worker=0,
        num_cpus_for_local_worker=1,
    )
)

algo = config.build()

for _ in range(5):
    result = algo.train()
    print(pretty_print(result))
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by ciroaceto** [comment]
The last error is caused by the execution of the `mask_forward_fn_torch` function twice in a row. The first of them when the `_forward_exploration` method is called. Within this method the `_foward_exploration` of `PPOTorchRLModule` class is called, which then returns `self._forward_inference(batch)`. This results in an error when the function `_check_batch` is executed.

One possible solution is to modify the method `_forward_exploration` of `TorchActionMaskRLM` class:

examples/action_masking_rlm.py:39
```
def _forward_exploration(self, batch, *args, **kwargs):
    return mask_forward_fn_torch(super()._forward_inference, batch, **kwargs)
```

It is also necessary to add **kwargs as argument of the `_forward_inference` method of `PPOTorchRLModule`:

ppo/torch/ppo_torch_rl_module.py:21
`def _forward_inference(self, batch: NestedDict, **kwargs) -> Dict[str, Any]:`

And here comes the next error during the calculation of vf_preds:

`ray.rllib.core.models.specs.checker.SpecCheckingError: input spec validation failed on TorchMLPEncoder.forward, Mismatch found in data element ('obs',), which is a TensorSpec: Expected data type <class 'torch.Tensor'> but found NestedDict.`

I'll dig into this one and add more comments if I find out how to solve it.

**Comment by ciroaceto** [comment]
This last issue is solved and the example is now running as expected. The `_compute_values` method of `PPOTorchRLModule` doesn't transform the observation of the batch and therefore it was a NestedDict. I added the following lines to solve it:

ppo/torch/ppo_torch_rl_module.py:95
```
if "action_mask" in batch[Columns.OBS]:
    batch[Columns.OBS] = batch[Columns.OBS]["observations"]
```

**Comment by ciroaceto** [comment]
@PhilippWillms: Do you mean using the `SingleAgentRLModuleSpec` but with another module class? Actually I haven't tried it. I'm just working with action masking environments. A normal environment with the new API stack (`SingleAgentEnvRunner`) runs fine. 

Are you having a similar issue? Which one exactly do you mean?

**Comment by PhilippWillms** [comment]
Following your initial reproduction script, the program runs through by **removing** explicit specifications of `.training(model={"uses_new_env_runners": True})` and `env_runner_cls= SingleAgentEnvRunner`. 

Is there a specific reason why you specify those config attributes?

**Comment by ciroaceto** [comment]
Yes, I want to use the [new API stack](https://docs.ray.io/en/latest/rllib/rllib-new-api-stack.html) and not the hybrid/old one.

**Comment by adadelta** [comment]
Still facing the same issue the new using the merged example.
