### ISSUE TITLE
[<Ray component: Core|RLlib|etc...>]

### ISSUE THREAD

**Issue by sebady** [ray-project/ray#51991]
### Description

It appears that that Ray docker images on docker hub are all anaconda3 based python.

```
docker run -it rayproject/ray:2.44.1-py310 which python
/home/ray/anaconda3/bin/python
```

For licensing reasons we'd prefer not to use anaconda3 based python.  Are there any plans to offer an alternative to anaconda3 based python with Ray docker images?

**Comment by thj08** [comment]
Hi, just wondering if there has been any update on this?  We're looking to avoid Anaconda.

**Comment by richardliaw** [comment]
cc @aslonnie

**Comment by pcmoritz** [comment]
On the anaconda issue, this is already fixed in https://github.com/ray-project/ray/pull/49990, see also https://github.com/ray-project/ray/issues/42077 (you can check that by calling `python`, it should say something like this:

<img width="710" height="74" alt="Image" src="https://github.com/user-attachments/assets/8e7fd0e1-dad7-4acf-b201-02d04edab1bf" />

For compatibility reasons, the conda-forge binaries are still living under `anaconda3`, which might be addressed going forward with the Ray image spec that @aslonnie is working on.

**Comment by thj08** [comment]
Thank you for the clarification!
So I can safely assume that Ray images are now free from anaconda3 licensing constraints.

**Comment by aslonnie** [comment]
recent and future ray images are and will be anaconda free.

**Comment by jeff303** [comment]
@aslonnie , do you mind pointing to a commit or tag where I can see an image that does not bundle Anaconda?  I checked out the nightly tag today and still see it there

```shell
docker run -it --rm --entrypoint sh rayproject/ray:nightly-cpu
$ ray --version
ray, version 3.0.0.dev0
$ ls /home/ray
anaconda3  pip-freeze.txt  requirements_compiled.txt
```

Or does the presence of `conda-forge` in the output of `conda info` mean that it's using Conda forge, and not the full Anaconda distribution?

**Comment by aslonnie** [comment]
hi @jeff303 , miniforge is installed in the same directory for backward compatibility reasons, but it is not anaconda anymore:

````
$ docker run -it --rm rayproject/ray:nightly-cpu head anaconda3/LICENSE.txt
Miniforge installer code uses BSD-3-Clause license as stated below.

Binary packages that come with it have their own licensing terms
and by installing miniforge you agree to the licensing terms of individual
packages as well. They include different OSI-approved licenses including
the GNU General Public License and can be found in pkgs/<pkg-name>/info/licenses
folders.

Miniforge installer comes with a bootstrapping executable that is used
when installing miniforge and is deleted after miniforge is installed.
````

by the way, we recommend using stable releases (or latest tag), rather than nightly.
