### ISSUE TITLE
[Core] `ray.init()` and `ray start` fails on Windows 11 in ray 2.45+

### ISSUE THREAD

**Issue by PhilippWillms** [ray-project/ray#52739]
### What happened + What you expected to happen

Hello,

after installing latest release 2.45 - no upgrade, removed older release before - I notice following fundamental issue.

Calling ray start --head in CLI leads to following console output.

> (py311-raynew) C:\Users\Philipp>ray start --head
> Usage stats collection is disabled.
> 
> Local node IP: 192.168.178.26
> 2025-05-02 16:53:36,888 ERROR services.py:1362 -- Failed to start the dashboard , return code 3221226505
> 2025-05-02 16:53:36,888 ERROR services.py:1387 -- Error should be written to 'dashboard.log' or 'dashboard.err'. We are printing the last 20 lines for you. See 'https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#logging-directory-structure' to find where the log file is.
> 2025-05-02 16:53:36,888 ERROR services.py:1397 -- Couldn't read dashboard.log file. Error: 'utf-8' codec can't decode byte 0xfc in position 40: invalid start byte. It means the dashboard is broken even before it initializes the logger (mostly dependency issues). Reading the dashboard.err file which contains stdout/stderr.
> 2025-05-02 16:53:36,888 ERROR services.py:1431 --
> The last 20 lines of C:\Users\Philipp\AppData\Local\Temp\ray\session_2025-05-02_16-53-32_217596_35728\logs\dashboard.err (it contains the error message from the dashboard):
> 
> Ray runtime started.

I am surprised that the app says "Ray runtime started", but I do not get` ray status` feedback.

> (py311-raynew) C:\Users\Philipp>ray status
> No cluster status. It may take a few seconds for the Ray internal services to start up.

Content of `dashboard.log` file

> 2025-05-02 16:53:33,639	ERROR dashboard.py:305 -- The dashboard on node PHILIPP-MAIN failed with the following error:
> Traceback (most recent call last):
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\dashboard\dashboard.py", line 247, in <module>
>     logging_utils.redirect_stdout_stderr_if_needed(
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\_private\logging_utils.py", line 48, in redirect_stdout_stderr_if_needed
>     sys.stderr = open_log(stderr_fileno, unbuffered=True, closefd=False)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\_private\utils.py", line 446, in open_log
>     stream = open(path, **kwargs)
>              ^^^^^^^^^^^^^^^^^^^^
> OSError: [WinError 6] Das Handle ist ungültig

Content of `dashboard.error` file

> [0m

### Versions / Dependencies

ray == 2.45
Windows == 26100.3915

### Reproduction script

`> ray start --head`

### Issue Severity

High: It blocks me from completing my task.

**Comment by kolcker** [comment]
I'm experiencing the same issue. Some addtional information from raylet.log 
```
[2025-05-04 12:06:23,685 I 32292 25604] (raylet.exe) agent_manager.cc:83: Agent process with name dashboard_agent exited, exit code 1.
[2025-05-04 12:06:23,685 E 32292 25604] (raylet.exe) agent_manager.cc:87: The raylet exited immediately because one Ray agent failed, agent_name = dashboard_agent.
The raylet fate shares with the agent. This can happen because
- The version of `grpcio` doesn't follow Ray's requirement. Agent can segfault with the incorrect `grpcio` version. Check the grpcio version `pip freeze | grep grpcio`.
- The agent failed to start because of unexpected error or port conflict. Read the log `cat /tmp/ray/session_latest/logs/{dashboard_agent|runtime_env_agent}.log`. You can find the log file structure here https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#logging-directory-structure.
- The agent is killed by the OS (e.g., out of memory).
[2025-05-04 12:06:23,686 I 32292 35296] (raylet.exe) main.cc:307: Raylet graceful shutdown triggered, reason = UNEXPECTED_TERMINATION, reason message = dashboard_agent failed and raylet fate-shares with it.
[2025-05-04 12:06:23,686 I 32292 35296] (raylet.exe) main.cc:310: Shutting down...
[2025-05-04 12:06:23,686 I 32292 35296] (raylet.exe) accessor.cc:515: Unregistering node node_id=2547f168cb62f79248f1ebdb4d408b1f1ac93d33f1d41244737eb966
[2025-05-04 12:06:23,689 I 32292 35296] (raylet.exe) accessor.cc:528: Finished unregistering node info, status = OK node_id=2547f168cb62f79248f1ebdb4d408b1f1ac93d33f1d41244737eb966
[2025-05-04 12:06:23,689 W 32292 19800] (raylet.exe) store.cc:368: Disconnecting client due to connection error with code 2: End of file
[2025-05-04 12:06:23,695 I 32292 35296] (raylet.exe) agent_manager.cc:116: Killing agent dashboard_agent, pid 8496.
[2025-05-04 12:06:23,695 I 32292 35296] (raylet.exe) agent_manager.cc:116: Killing agent runtime_env_agent, pid 6348.
[2025-05-04 12:06:23,696 I 32292 9940] (raylet.exe) agent_manager.cc:83: Agent process with name runtime_env_agent exited, exit code 1067.
[2025-05-04 12:06:23,697 I 32292 35296] (raylet.exe) io_service_pool.cc:48: IOServicePool is stopped.
[0m[0m[2025-05-04 12:06:23,915 I 32292 35296] (raylet.exe) stats.h:120: Stats module has shutdown.
```
Updating of grpcio version to 1.72 doesn't help. 
Current environment works fine with ray 2.44.1. 

**Versions / Dependencies**
ray == 2.45
Windows == 26100.3915

**Issue Severity**
High: It blocks me from completing my task.

Let me know if any additional information will be helpful.

**Comment by kolcker** [comment]
Dear @masoudcharkhabi, @sven1977, @simonsays1980, 
It looks like, this issue is a **blocker** for users that are making fast experiments on the Windows OS. Issue appears from ray version 2.45. As I said in my previous post ray 2.44.1 is stable. This is for sure not **utf-8 decoding issue**.

Script to reproduce issue. Disabling the dashboard doesn't help. The same behavior for ray.init()
```
import ray
ray.init(include_dashboard=False)
```
Script error. The same exception could be found in the dashboard.log
```
2025-05-14 12:45:04,169	ERROR services.py:1362 -- Failed to start the dashboard , return code 3221226505
2025-05-14 12:45:04,169	ERROR services.py:1387 -- Error should be written to 'dashboard.log' or 'dashboard.err'. We are printing the last 20 lines for you. See 'https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#logging-directory-structure' to find where the log file is.
2025-05-14 12:45:04,174	ERROR services.py:1431 -- 
The last 20 lines of C:\WINDOWS\TEMP\ray\session_2025-05-14_12-44-59_804590_5292\logs\dashboard.log (it contains the error message from the dashboard): 
Traceback (most recent call last):
  File "E:\python_venvs\prs\.venv\Lib\site-packages\ray\dashboard\dashboard.py", line 247, in <module>
    logging_utils.redirect_stdout_stderr_if_needed(
  File "E:\python_venvs\prs\.venv\Lib\site-packages\ray\_private\logging_utils.py", line 48, in redirect_stdout_stderr_if_needed
    sys.stderr = open_log(stderr_fileno, unbuffered=True, closefd=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python_venvs\prs\.venv\Lib\site-packages\ray\_private\utils.py", line 446, in open_log
    stream = open(path, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid

2025-05-14 12:45:04,326	INFO worker.py:1888 -- Started a local Ray instance.
[2025-05-14 12:45:07,189 E 5292 16792] core_worker.cc:513: Failed to register worker to Raylet: IOError: [RayletClient] Unable to register worker with raylet. Unknown error worker_id=01000000ffffffffffffffffffffffffffffffffffffffffffffffff
```
Log raylet.err
```
....
[2025-05-14 13:08:45,360 I 32516 14120] (raylet.exe) worker_pool.cc:527: Started worker process with pid 27440, the token is 26
[2025-05-14 13:08:45,364 I 32516 14120] (raylet.exe) worker_pool.cc:527: Started worker process with pid 9280, the token is 27
[2025-05-14 13:08:45,368 I 32516 14120] (raylet.exe) worker_pool.cc:527: Started worker process with pid 2608, the token is 28
[2025-05-14 13:08:45,372 I 32516 14120] (raylet.exe) worker_pool.cc:527: Started worker process with pid 6768, the token is 29
[2025-05-14 13:08:45,376 I 32516 14120] (raylet.exe) worker_pool.cc:527: Started worker process with pid 31592, the token is 30
[2025-05-14 13:08:45,380 I 32516 14120] (raylet.exe) worker_pool.cc:527: Started worker process with pid 32684, the token is 31
[2025-05-14 13:08:47,073 I 32516 11484] (raylet.exe) agent_manager.cc:83: Agent process with name dashboard_agent exited, exit code -1073740791.
[2025-05-14 13:08:47,073 E 32516 11484] (raylet.exe) agent_manager.cc:87: The raylet exited immediately because one Ray agent failed, agent_name = dashboard_agent.
The raylet fate shares with the agent. This can happen because
- The version of `grpcio` doesn't follow Ray's requirement. Agent can segfault with the incorrect `grpcio` version. Check the grpcio version `pip freeze | grep grpcio`.
- The agent failed to start because of unexpected error or port conflict. Read the log `cat /tmp/ray/session_latest/logs/{dashboard_agent|runtime_env_agent}.log`. You can find the log file structure here https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#logging-directory-structure.
- The agent is killed by the OS (e.g., out of memory).
[2025-05-14 13:08:47,075 I 32516 14120] (raylet.exe) main.cc:307: Raylet graceful shutdown triggered, reason = UNEXPECTED_TERMINATION, reason message = dashboard_agent failed and raylet fate-shares with it.
[2025-05-14 13:08:47,075 I 32516 14120] (raylet.exe) main.cc:310: Shutting down...
[2025-05-14 13:08:47,075 I 32516 14120] (raylet.exe) accessor.cc:515: Unregistering node node_id=b98f0b68d473db175d08c36ea95ca35ce7abbea5dd07edb0f301695f
[2025-05-14 13:08:47,080 I 32516 14120] (raylet.exe) accessor.cc:528: Finished unregistering node info, status = OK node_id=b98f0b68d473db175d08c36ea95ca35ce7abbea5dd07edb0f301695f
[2025-05-14 13:08:47,080 W 32516 31440] (raylet.exe) store.cc:368: Disconnecting client due to connection error with code 2: End of file
[2025-05-14 13:08:47,115 I 32516 14120] (raylet.exe) agent_manager.cc:116: Killing agent dashboard_agent, pid 27564.
[2025-05-14 13:08:47,115 I 32516 14120] (raylet.exe) agent_manager.cc:116: Killing agent runtime_env_agent, pid 15252.
[2025-05-14 13:08:47,122 I 32516 9552] (raylet.exe) agent_manager.cc:83: Agent process with name runtime_env_agent exited, exit code 1067.
[2025-05-14 13:08:47,123 I 32516 14120] (raylet.exe) io_service_pool.cc:48: IOServicePool is stopped.
[2025-05-14 13:08:47,277 I 32516 14120] (raylet.exe) stats.h:120: Stats module has shutdown.
[2025-05-14 13:08:47,278 E 32516 14120] (raylet.exe) logging.cc:496: *** SIGSEGV received at time=1747217327 ***
....
```
here is results from pip freeze
```
absl-py==2.2.2
aiohappyeyeballs==2.6.1
aiohttp==3.11.18
aiohttp-cors==0.8.1
aiosignal==1.3.2
annotated-types==0.7.0
attrs==25.3.0
cachetools==5.5.2
certifi==2025.4.26
charset-normalizer==3.4.2
click==8.2.0
cloudpickle==3.1.1
colorama==0.4.6
colorful==0.5.6
contourpy==1.3.2
cycler==0.12.1
distlib==0.3.9
dm-tree==0.1.9
Farama-Notifications==0.0.4
filelock==3.18.0
fonttools==4.58.0
frozenlist==1.6.0
fsspec==2025.3.2
google-api-core==2.24.2
google-auth==2.40.1
googleapis-common-protos==1.70.0
grpcio==1.71.0
gymnasium==1.0.0
idna==3.10
Jinja2==3.1.4
joblib==1.5.0
jsonschema==4.23.0
jsonschema-specifications==2025.4.1
kiwisolver==1.4.8
lz4==4.4.4
MarkupSafe==2.1.5
matplotlib==3.10.3
mpmath==1.3.0
msgpack==1.1.0
multidict==6.4.3
networkx==3.4.2
numpy==2.2.5
opencensus==0.11.4
opencensus-context==0.1.3
ormsgpack==1.7.0
packaging==25.0
pandas==2.2.3
pillow==11.2.1
platformdirs==4.3.8
prometheus_client==0.21.1
propcache==0.3.1
proto-plus==1.26.1
protobuf==6.30.2
py-spy==0.4.0
pyarrow==20.0.0
pyasn1==0.6.1
pyasn1_modules==0.4.2
pydantic==2.11.4
pydantic_core==2.33.2
pyparsing==3.2.3
python-dateutil==2.9.0.post0
pytz==2025.2
PyYAML==6.0.2
ray==2.46.0
referencing==0.36.2
requests==2.32.3
rpds-py==0.24.0
rsa==4.9.1
scikit-learn==1.6.1
scipy==1.15.3
six==1.17.0
smart-open==7.1.0
sympy==1.13.3
ta==0.11.0
tensorboardX==2.6.2.2
threadpoolctl==3.6.0
torch==2.8.0.dev20250512+cu128
torchaudio==2.6.0.dev20250513+cu128
torchvision==0.22.0.dev20250513+cu128
typing-inspection==0.4.0
typing_extensions==4.13.2
tzdata==2025.2
urllib3==2.4.0
virtualenv==20.31.2
wrapt==1.17.2
yarl==1.20.0
```
Additional information:

- Windows OS Build: 26100.2605
- Experiment isolation: I made a clean environment and reinstalled all ray packages and dependencies to potentially prevent problems with particular updates of packages.
- Updating grpcio from 1.71.0 to 1.72.0 or decreasing down to grpcio==1.66.2 doesn't help.
- This is not an antivirus, firewall, out of memory or permission issue.
- This is for sure not an utf-8 decoding issue.

Expected result:

- Increase priority for this issue. I guess it's P0/P1
- Fix regression issue and unblock possibility of using ray 2.45+ on the Windows OS
- Fix issue with include_dashboard=False for ray.init. I guess it should disable the dashboard.
- Please provide a workaround, if fixing this issue requires a lot of time.

Please let me know if any additional information will be helpful.
Thanks in advance.

**Comment by PhilippWillms** [comment]
@kolcker: Thanks for your contribution to the error defintion. Changed the title of the GH issue accordingly.

**Comment by DanZee** [comment]
@masoudcharkhabi should this not include the "bug" label as well? It prevents Ray from starting altogether on Windows.

The issue is with redirecting stderr to a file - I'm guess this is closed somewhere. Possibly in [PR 51731](https://github.com/ray-project/ray/pull/51731) - @dentiny ?

**Comment by PhilippWillms** [comment]
*push* - I would consider this topic as a release blocker for windows users. At least, it would be great to get to know a workaround, if applicable.

**Comment by mattip** [comment]
CI runs on windows succeed, so there is something different in your local machine setup. Could you modify `C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray_private\logging_utils.py` to try, except an error around the line `sys.stderr = ...` and print the values of `stderr_fileno`, `stderr_filepath`, `rotation_bytes`, `rotation_backup_count`?

**Comment by PhilippWillms** [comment]
hi @mattip ,

I added strategic logging and got the following insights.

- stdout file number is 1, stderror file number is 2.
- Rotation bytes are always 0, backup count are always 1.
- After complete hard `ray stop` and no ray process running at all, the log rotation init works for stdout, but not for stderr.
- dashboard.out is opened as fully empty file (0 bytes). dashboard.err gets 1 initial byte which is shown in Windows Cmd as "[0m".


See console log.

> 2025-06-01 14:52:27,661	INFO logging_utils.py:32 -- Redirected stdout to C:\Users\Philipp\AppData\Local\Temp\ray\session_2025-06-01_14-52-26_265781_2264\logs\dashboard.out with rotation bytes 0 and backup count 1.
> 2025-06-01 14:52:27,662	INFO logging_utils.py:44 -- Redirected stderr to C:\Users\Philipp\AppData\Local\Temp\ray\session_2025-06-01_14-52-26_265781_2264\logs\dashboard.err with rotation bytes 0 and backup count 1.
> 2025-06-01 14:52:27,663	INFO logging_utils.py:51 -- file descriptor 1 initialized for stdout.
> 2025-06-01 14:52:27,663	INFO logging_utils.py:53 -- file descriptor 2 initialized for stderr.
> 2025-06-01 14:52:27,665	INFO utils.py:444 -- Calling open_log with path=1, unbuffered=True and kwargs={'closefd': False}
> 2025-06-01 14:52:27,665	INFO utils.py:451 -- Opening log file 1 with unbuffered=True and kwargs={'closefd': False, 'buffering': 1, 'mode': 'a', 'encoding': 'utf-8'}
> 2025-06-01 14:52:27,665	INFO utils.py:458 -- For path 1, using unbuffered stream.
> 2025-06-01 14:52:27,666	INFO logging_utils.py:60 -- Redirected sys.stdout to file descriptor 1.
> 2025-06-01 14:52:27,666	INFO utils.py:444 -- Calling open_log with path=2, unbuffered=True and kwargs={'closefd': False}
> 2025-06-01 14:52:27,666	INFO utils.py:451 -- Opening log file 2 with unbuffered=True and kwargs={'closefd': False, 'buffering': 1, 'mode': 'a', 'encoding': 'utf-8'}
> 2025-06-01 14:52:27,666	ERROR utils.py:464 -- Failed to open log file 2: [WinError 6] Das Handle ist ungültig
> 2025-06-01 14:52:27,668	ERROR dashboard.py:305 -- The dashboard on node PHILIPP-MAIN failed with the following error:
> Traceback (most recent call last):
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\dashboard\dashboard.py", line 247, in <module>
>     logging_utils.redirect_stdout_stderr_if_needed(
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\_private\logging_utils.py", line 63, in redirect_stdout_stderr_if_needed
>     sys.stderr = open_log(stderr_fileno, unbuffered=True, closefd=False)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\_private\utils.py", line 456, in open_log
>     stream = open(path, **kwargs)
>              ^^^^^^^^^^^^^^^^^^^^
> OSError: [WinError 6] Das Handle ist ungültig
>

**Comment by PhilippWillms** [comment]
For your information, in ray version 2.44.1, the same spot looks like this:

> 2025-06-01 19:38:08,383 INFO utils.py:446 -- Calling open_log with path=C:\Users\Philipp\AppData\Local\Temp\ray\session_2025-06-01_19-38-07_810473_21192\logs\dashboard.err, unbuffered=False and kwargs={}
> 2025-06-01 19:38:08,383 INFO utils.py:453 -- Opening log file C:\Users\Philipp\AppData\Local\Temp\ray\session_2025-06-01_19-38-07_810473_21192\logs\dashboard.err with unbuffered=False and kwargs={'buffering': 1, 'mode': 'a', 'encoding': 'utf-8'}
> 2025-06-01 19:38:08,385 INFO utils.py:462 -- For path C:\Users\Philipp\AppData\Local\Temp\ray\session_2025-06-01_19-38-07_810473_21192\logs\dashboard.err, using buffered stream.

**Comment by kolcker** [comment]
Hello @mattip, 
I made changes in the logging_utils.py and utils.py in the new ray project. There are no other libs in the project. 
I'm not using anaconda and my path to the logging_utils loos like `E:\projects\ray_test\.venv\Lib\site-packages\ray\_private\logging_utils.py` but not ` ..\Lib\site-packages\ray_private\logging_utils.py`

Script to reproduce:
```
import ray
ray.init(include_dashboard=False)
```

Changes in the logging_utils.py:

```
def redirect_stdout_stderr_if_needed(
    stdout_filepath: str,
    stderr_filepath: str,
    rotation_bytes: int,
    rotation_backup_count: int,
):
    """This function sets up redirection for stdout and stderr if needed, based on the given rotation parameters.

    params:
    stdout_filepath: the filepath stdout will be redirected to; if empty, stdout will not be redirected.
    stderr_filepath: the filepath stderr will be redirected to; if empty, stderr will not be redirected.
    rotation_bytes: number of bytes which triggers file rotation.
    rotation_backup_count: the max size of rotation files.
    """
    print(    stdout_filepath,
    stderr_filepath,
    rotation_bytes,
    rotation_backup_count,)

    # Setup redirection for stdout and stderr.
    if stdout_filepath:
        StreamRedirector.redirect_stdout(
            stdout_filepath,
            rotation_bytes,
            rotation_backup_count,
            False,  # tee_to_stdout
            False,  # tee_to_stderr
        )
    if stderr_filepath:
        StreamRedirector.redirect_stderr(
            stderr_filepath,
            rotation_bytes,
            rotation_backup_count,
            False,  # tee_to_stdout
            False,  # tee_to_stderr
        )

    # Setup python system stdout/stderr.
    stdout_fileno = sys.stdout.fileno()
    stderr_fileno = sys.stderr.fileno()
    print("stdout_filepath", stdout_filepath)
    print("stderr_filepath", stderr_filepath)
    print("stdout_fileno:", stdout_fileno)
    print("stderr_fileno:", stderr_fileno)
    print("rotation_bytes:", rotation_bytes)
    print("rotation_backup_count:", rotation_backup_count)

    # We also manually set sys.stdout and sys.stderr because that seems to
    # have an effect on the output buffering. Without doing this, stdout
    # and stderr are heavily buffered resulting in seemingly lost logging
    # statements. We never want to close the stdout file descriptor, dup2 will
    # close it when necessary and we don't want python's GC to close it.
    sys.stdout = open_log(stdout_fileno, unbuffered=True, closefd=False)
    sys.stderr = open_log(stderr_fileno, unbuffered=True, closefd=False)
```
utils.py open_log method
```
def open_log(path, unbuffered=False, **kwargs):
    """
    Opens the log file at `path`, with the provided kwargs being given to
    `open`.
    """
    # Disable buffering, see test_advanced_3.py::test_logging_to_driver
    kwargs.setdefault("buffering", 1)
    kwargs.setdefault("mode", "a")
    kwargs.setdefault("encoding", "utf-8")
    print("open_log method debug data")
    print("path:", path)
    print("kwargs", kwargs)
    stream = open(path, **kwargs)
    if unbuffered:
        return Unbuffered(stream)
    else:
        return stream
```
Please find attached archive with ray sessions logs.
[session_2025-06-02_11-09-49_902338_28444.zip](https://github.com/user-attachments/files/20547654/session_2025-06-02_11-09-49_902338_28444.zip)

Hope this will help. Please let me know if any additional information is needed.

**Comment by mattip** [comment]
Assuming this is a regression from 2.44, maybe worth trying to bisect where this started failing by installing the [daily builds](https://docs.ray.io/en/latest/ray-overview/installation.html#installing-from-a-specific-commit) to pinpiont where it started failing

**Comment by kolcker** [comment]
It looks like, I localized error even without ray.init. 
```
from ray._private.utils import open_log
from ray._raylet import StreamRedirector
import sys, logging

# Setup redirection for stdout and stderr.
stdout_filepath = 'e:/projects/ray_test/stdout.log'
stderr_filepath = 'e:/projects/ray_test/stderr.log'

print(sys.stdout)
print(sys.platform)

if stdout_filepath:
    StreamRedirector.redirect_stdout(
        stdout_filepath,
        0, #args.logging_rotate_bytes if sys.platform != "win32" else 0,
        1, # args.logging_rotate_backup_count if sys.platform != "win32" else 1
        False,  # tee_to_stdout
        False,  # tee_to_stderr
    )

stdout_fileno = sys.stdout.fileno()
print("stdout_fileno", stdout_fileno, file=sys.stderr)
print("print to stdout")
sys.stdout = open_log(stdout_fileno, unbuffered=True, closefd=False)
```
Based on my investigations problem inside `StreamRedirector.redirect_stdout, StreamRedirector.redirect_stderr`. As soon as these methods called we are receiving bad descriptor for writing to log files. 

Here is an output: 
```
E:\projects\ray_test\.venv12\Scripts\python.exe E:\projects\ray_test\test.py 
stdout_fileno 1
Traceback (most recent call last):
  File "E:\projects\ray_test\test.py", line 25, in <module>
    print("print to stdout")
OSError: [Errno 9] Bad file descriptor
<_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
win32

Process finished with exit code -1073740791 (0xC0000409)
```

Most likely regression issue appeared somewhere around https://github.com/ray-project/ray/commit/eec751374cd308d265af4e41604e65b8fde1fea9

Please let me know if any information from debugger will be helpful.

@mattip please take a look.

**Comment by PhilippWillms** [comment]
Further finding: The issue does not occur on Windows 10 (Version 10.0.19045 Build 19045).

Here, ray 2.45 shows following behavior for the StreamRedirection:

> 2025-06-02 20:59:51,299	INFO logging_utils.py:42 -- File descriptor for stdout: 1
> 2025-06-02 20:59:51,299	INFO logging_utils.py:44 -- File descriptor for stderr: 2
> 2025-06-02 20:59:51,300	INFO utils.py:443 -- Calling open_log with path=1, unbufffered=True and kwargs={'closefd': False}
> 2025-06-02 20:59:51,300	INFO utils.py:447 -- Opening log file at 1 with kwargs={'closefd': False, 'buffering': 1, 'mode': 'a', 'encoding': 'utf-8'}
> 2025-06-02 20:59:51,300	INFO utils.py:450 -- Wrapping stream <_io.TextIOWrapper name=1 mode='a' encoding='utf-8'> with Unbuffered
> 2025-06-02 20:59:51,300	INFO utils.py:443 -- Calling open_log with path=2, unbufffered=True and kwargs={'closefd': False}
> 2025-06-02 20:59:51,300	INFO utils.py:447 -- Opening log file at 2 with kwargs={'closefd': False, 'buffering': 1, 'mode': 'a', 'encoding': 'utf-8'}
> 2025-06-02 20:59:51,300	INFO utils.py:450 -- Wrapping stream <_io.TextIOWrapper name=2 mode='a' encoding='utf-8'> with Unbuffered

**Comment by AndySung320** [comment]
Hi, I'm new to Ray development and encountered the same Windows issue while following the official development setup guide.

### My Experience:
- **Background:** First-time Ray contributor trying to set up development environment
- **Following:** https://docs.ray.io/en/master/ray-contribute/development.html
- **OS:** Windows 11 with conda environment

### Issues Encountered:
- **Ray 3.0.0.dev0 (nightly):** Failed with import errors and version compatibility issues
- **Ray 2.45+:** Similar initialization problems as reported in this issue

### Working Solution:
After reading this thread, I downgraded to Ray 2.44.0, and everything worked as expected — no import errors, and ray.init() runs successfully.
Just sharing my experience in case it helps other Windows users or maintainers trying to reproduce the issue.
```bash
pip install "ray[default]==2.44.0"
git checkout ray-2.44.0  
python python/ray/setup-dev.py -y

**Comment by czgdp1807** [comment]
I am able to reproduce this error,

```powershell
(ray-dev) PS C:\Users\czgdp1807\Anyscale\ray\python> ray start --head
Enable usage stats collection? This prompt will auto-proceed in 10 seconds to avoid blocking cluster startup. Confirm [Y/n]:
Usage stats collection is enabled. To disable this, add `--disable-usage-stats` to the command that starts the cluster, or run the following command: `ray disable-usage-stats` before starting the cluster. See https://docs.ray.io/en/master/cluster/usage-stats.html for more details.

Local node IP: 127.0.0.1
2025-06-05 16:10:27,199 ERROR services.py:1355 -- Failed to start the dashboard , return code 3221226505
2025-06-05 16:10:27,201 ERROR services.py:1380 -- Error should be written to 'dashboard.log' or 'dashboard.err'. We are printing the last 20 lines for you. See 'https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#logging-directory-structure' to find where the log file is.
2025-06-05 16:10:27,219 ERROR services.py:1424 --
The last 20 lines of C:\Users\CZGDP1~1\AppData\Local\Temp\ray\session_2025-06-05_16-10-17_593443_6000\logs\dashboard.log (it contains the error message from the dashboard):
Traceback (most recent call last):
  File "c:\users\czgdp1807\anyscale\ray\python\ray\dashboard\dashboard.py", line 246, in <module>
    logging_utils.redirect_stdout_stderr_if_needed(
  File "c:\users\czgdp1807\anyscale\ray\python\ray\_private\logging_utils.py", line 49, in redirect_stdout_stderr_if_needed
    sys.stderr = open_log(stderr_fileno, unbuffered=True, closefd=False)
  File "c:\users\czgdp1807\anyscale\ray\python\ray\_private\utils.py", line 444, in open_log
    stream = open(path, **kwargs)
OSError: [WinError 6] The handle is invalid



--------------------
Ray runtime started.
--------------------

Next steps

  To connect to this Ray cluster:
    import ray
    ray.init()

  To terminate the Ray runtime, run
    ray stop

  To view the status of the cluster, use
    ray status
```

Let me see what's going on.

**Comment by jjyao** [comment]
We are actively working on this together with @mattip, @czgdp1807 . Will give an update in a day or two. In the meantime, are you able to use WSL?

**Comment by czgdp1807** [comment]
So here's what I figured out. The root cause is the following error,

```powershell
(ray-dev) PS C:\Users\czgdp1807\Anyscale\ray> ray start --head
Usage stats collection is enabled. To disable this, add `--disable-usage-stats` to the command that starts the cluster, or run the following command: `ray disable-usage-stats` before starting the cluster. See https://docs.ray.io/en/master/cluster/usage-stats.html for more details.

Local node IP: 127.0.0.1
2025-06-11 17:09:17,586 ERROR services.py:1355 -- Failed to start the dashboard , return code 3221226505
2025-06-11 17:09:17,586 ERROR services.py:1380 -- Error should be written to 'dashboard.log' or 'dashboard.err'. We are printing the last 20 lines for you. See 'https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#logging-directory-structure' to find where the log file is.
2025-06-11 17:09:17,602 ERROR services.py:1424 --
The last 20 lines of C:\Users\CZGDP1~1\AppData\Local\Temp\ray\session_2025-06-11_17-09-12_698167_11108\logs\dashboard.log (it contains the error message from the dashboard):
Traceback (most recent call last):
  File "c:\users\czgdp1807\anyscale\ray\python\ray\dashboard\dashboard.py", line 246, in <module>
    logging_utils.redirect_stdout_stderr_if_needed(
  File "c:\users\czgdp1807\anyscale\ray\python\ray\_private\logging_utils.py", line 52, in redirect_stdout_stderr_if_needed
    sys.stderr = open_log(stderr_fileno, unbuffered=True, closefd=False)
  File "c:\users\czgdp1807\anyscale\ray\python\ray\_private\utils.py", line 322, in open_log
    raise e
  File "c:\users\czgdp1807\anyscale\ray\python\ray\_private\utils.py", line 318, in open_log
    stream = open(path, **kwargs)
OSError: [WinError 6] The handle is invalid
```

Now note the following points,

1. The `ray status` command queries for `DEBUG_AUTOSCALING_STATUS` and `DEBUG_AUTOSCALING_ERROR` in ray's KV store.

https://github.com/ray-project/ray/blob/3173e308b43bc65c7cdd2365e792b2d38e6ee6e7/python/ray/scripts/scripts.py#L2120-L2121

2. `DEBUG_AUTOSCALING_STATUS ` is registered in `monitor.py`,

https://github.com/ray-project/ray/blob/3173e308b43bc65c7cdd2365e792b2d38e6ee6e7/python/ray/autoscaler/_private/monitor.py#L446-L449

3. However we never reach the above lines in `monitor.py` because `OSError: [WinError 6] The handle is invalid` happens in the following call,

https://github.com/ray-project/ray/blob/3173e308b43bc65c7cdd2365e792b2d38e6ee6e7/python/ray/autoscaler/_private/monitor.py#L718-L724

4. Within the above call, the following lines set `stdout_file` and `stderr_file` to `open(os.devnull, "w")`,

https://github.com/ray-project/ray/blob/d57f4a0502f61868abefca6c009c2927cf3b0e93/python/ray/_private/services.py#L2298-L2304

Usage of `open(os.devnull, "w")` leads to `OSError: [WinError 6] The handle is invalid` on Windows 11.

To verify the same I wrote a minimum reproducible python example,

```python
import sys, os

kwargs = {"closefd": False}
kwargs["buffering"] = 1
kwargs["mode"] = "a"
kwargs["encoding"] = "utf-8"
stderr_fileno = open(os.devnull, "w").fileno()

stream = open(stderr_fileno, **kwargs)
```

```powershell
(ray-dev) PS C:\Users\czgdp1807\Anyscale> python debug.py
Traceback (most recent call last):
  File "C:\Users\czgdp1807\Anyscale\debug.py", line 9, in <module>
    stream = open(stderr_fileno, **kwargs)
OSError: [WinError 6] The handle is invalid
```

**Comment by jjyao** [comment]
@czgdp1807

> Within the above call, the following lines set stdout_file and stderr_file to open(os.devnull, "w"),

`logging_utils.redirect_stdout_stderr_if_needed` and `stdout_file = open(os.devnull, "w")` are actually called by different processes. I removed `stdout_file = open(os.devnull, "w")` and the error still happened.

**Comment by PhilippWillms** [comment]
@kolcker : For me it is now working with ray release 2.47. Kindly try again with latest version published on Friday.

I am interested in what was now the root cause and the fix, though.

**Comment by kolcker** [comment]
@PhilippWillms thank you for information. 

I still have the same issue after the clean installation of ray 2.47. 
Installation `pip install -U "ray[train,tune]"` to the new Virtualenv

Script to reproduce
```
import ray
ray.init(include_dashboard=False)
```
the same error
```
E:\projects\ray_test\.venv15\Scripts\python.exe E:\projects\ray_test\test3.py 
2025-06-15 18:07:39,219	ERROR services.py:1355 -- Failed to start the dashboard , return code 3221226505
2025-06-15 18:07:39,219	ERROR services.py:1380 -- Error should be written to 'dashboard.log' or 'dashboard.err'. We are printing the last 20 lines for you. See 'https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#logging-directory-structure' to find where the log file is.
2025-06-15 18:07:39,224	ERROR services.py:1424 -- 
The last 20 lines of C:\WINDOWS\TEMP\ray\session_2025-06-15_18-07-34_072267_35384\logs\dashboard.log (it contains the error message from the dashboard): 
Traceback (most recent call last):
  File "E:\projects\ray_test\.venv15\Lib\site-packages\ray\dashboard\dashboard.py", line 246, in <module>
    logging_utils.redirect_stdout_stderr_if_needed(
  File "E:\projects\ray_test\.venv15\Lib\site-packages\ray\_private\logging_utils.py", line 49, in redirect_stdout_stderr_if_needed
    sys.stderr = open_log(stderr_fileno, unbuffered=True, closefd=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\projects\ray_test\.venv15\Lib\site-packages\ray\_private\utils.py", line 444, in open_log
    stream = open(path, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid

2025-06-15 18:07:39,414	INFO worker.py:1917 -- Started a local Ray instance.
[2025-06-15 18:07:42,064 E 35384 36528] core_worker.cc:513: Failed to register worker to Raylet: IOError: [RayletClient] Unable to register worker with raylet. Unknown error worker_id=01000000ffffffffffffffffffffffffffffffffffffffffffffffff
```
requirements.txt 
```
annotated-types==0.7.0
attrs==25.3.0
certifi==2025.6.15
charset-normalizer==3.4.2
click==8.2.1
colorama==0.4.6
filelock==3.18.0
fsspec==2025.5.1
idna==3.10
jsonschema==4.24.0
jsonschema-specifications==2025.4.1
msgpack==1.1.1
numpy==2.3.0
packaging==25.0
pandas==2.3.0
protobuf==6.31.1
pyarrow==20.0.0
pydantic==2.11.7
pydantic_core==2.33.2
python-dateutil==2.9.0.post0
pytz==2025.2
PyYAML==6.0.2
ray==2.47.0
referencing==0.36.2
requests==2.32.4
rpds-py==0.25.1
six==1.17.0
tensorboardX==2.6.4
typing-inspection==0.4.1
typing_extensions==4.14.0
tzdata==2025.2
urllib3==2.4.0
```

Ray team, please let us know if you have any updates regarding status of this issue.

Thanks in advance.

**Comment by jjyao** [comment]
I have a workaround and I'm putting up a PR.

**Comment by jjyao** [comment]
@PhilippWillms do you have an OS upgrade or msvc upgrade?

**Comment by PhilippWillms** [comment]
> [@PhilippWillms](https://github.com/PhilippWillms) do you have an OS upgrade or msvc upgrade?

Good point. Checking the details, I see that now my Windows has build ID **26100.4351**. Updates which were installed last Friday, 2025-06-11, are KB5061935 and KB5063060.

**Comment by jjyao** [comment]
@PhilippWillms I guess it's hard to rollback and see if it's fixed by the upgrade 😂  

@kolcker could you see if upgrading Windows fixes the issue for you or not?

**Comment by kolcker** [comment]
@jjyao my Win 11 is up to date (all available updates are installed). 

Here is a list of recent updates from my side. 

![Image](https://github.com/user-attachments/assets/3e2bcd54-8ef4-431c-a107-9e875c9af759)

I do have KB5061935, but don't have KB5063060. 

Issue still exists on my side.

**Comment by jjyao** [comment]
@kolcker Could you try the following wheel depending on your Python version and see if it works for you:

https://ray-ci-artifact-pr-public.s3.amazonaws.com/d390abc917370eb92624c317ff8faecea632fe2e/tmp%5Cartifacts%5Cpython%5Cdist%5Cdist%5Cray-3.0.0.dev0-cp312-cp312-win_amd64.whl

https://ray-ci-artifact-pr-public.s3.amazonaws.com/d390abc917370eb92624c317ff8faecea632fe2e/tmp%5Cartifacts%5Cpython%5Cdist%5Cdist%5Cray-3.0.0.dev0-cp311-cp311-win_amd64.whl

https://ray-ci-artifact-pr-public.s3.amazonaws.com/d390abc917370eb92624c317ff8faecea632fe2e/tmp%5Cartifacts%5Cpython%5Cdist%5Cdist%5Cray-3.0.0.dev0-cp310-cp310-win_amd64.whl

https://ray-ci-artifact-pr-public.s3.amazonaws.com/d390abc917370eb92624c317ff8faecea632fe2e/tmp%5Cartifacts%5Cpython%5Cdist%5Cdist%5Cray-3.0.0.dev0-cp39-cp39-win_amd64.whl

**Comment by jjyao** [comment]
@PhilippWillms @kolcker and others, since you are all windows users and I'd like to get your options on #53924. It'd be much appreciated if you could leave comments sharing your thoughts on this topic.

**Comment by Nick346-surf** [comment]
I'm running Windows 11 Build 22631.5472 and Ray 2.47.1 and still get the issue when stating Ray (ray start --head) : **_OSError: [WinError 6] The handle is invalid_**
Any recommendation on what to do to resolve the issue. It was working ok on Windows 10 OS, but lately corporate made us upgrading to Windows 11.
Right now, i'm stuck because of this. Any help would be greatly appreciated. Thanks

**Comment by jjyao** [comment]
@Nick346-surf the fix will be released as part of 2.48 or you can use nightly wheel for now.

**Comment by OngartCharoenpaiboonsin** [comment]
.

**Comment by kolcker** [comment]
> > @PhilippWillms we will release it as 2.48 which should be released in 2-3 weeks. Would that work?
> 
> Ok, fine for me.

@jjyao please let me know if you have any timeline for releasing 2.48. It's almost 1 month since your last comment. It's become critical for me to have this issue fixed in stable release. 

Thanks in advance.

**Comment by jjyao** [comment]
Hi @kolcker 2.48 is cut and will be released within a few days.

**Comment by kolcker** [comment]
Hello @jjyao, thank you. We will be waiting for new release.

**Comment by OngartCharoenpaiboonsin** [comment]
.

**Comment by Hydraxx10** [comment]
Pleasee help with this error, after installing version 2.48 on windows 11 i get this after training:
`config = (
    SACConfig()
    .environment(
        TradingEnv,  # NOT TradingEnv() or a wrapped function unless using register_env
        env_config={
            "train": train,
            "close": close,
            "close2": close2,
            "highs": highs,
            "lows": lows,
            "starting_index": 0,
        }
    )
    # .callbacks(EpisodeReturn)
    .training(
        gamma=0.9,
        actor_lr=0.001,
        critic_lr=0.002,
        train_batch_size_per_learner=32,
    )
    .env_runners(
        rollout_fragment_length=1000,  # Collect more steps
        # num_env_runners=1,
    )
)
config = config.framework("torch")
for i in range(10):
    algo.train()
env = TradingEnv({
            "train": train,
            "close": close,
            "close2": close2,
            "highs": highs,
            "lows": lows,
            "starting_index": 10,
        })
policy = algo.get_policy()
total_reward = 0
done = False 
state, _ = env.reset()
while not done:
    state, reward, done, _ = loaded_policy.compute_single_action(state)
    total_reward += reward`

Results in 

` policy = algo.get_policy()
     10 total_reward = 0
     11 done = False 

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\ray\rllib\algorithms\algorithm.py:2398, in Algorithm.get_policy(self, policy_id)
   2391 @OldAPIStack
   2392 def get_policy(self, policy_id: PolicyID = DEFAULT_POLICY_ID) -> Policy:
   2393     """Return policy for the specified id, or None.
   2394 
   2395     Args:
   2396         policy_id: ID of the policy to return.
   2397     """
-> 2398     return self.env_runner.get_policy(policy_id)

AttributeError: 'SingleAgentEnvRunner' object has no attribute 'get_policy' `

**Comment by jjyao** [comment]
@Hydraxx10 could you file a separate issue for the latest error since it's different from the issue this ticket is about. cc @sven1977 i think it's rllib issue now.
