### ISSUE TITLE
Global CUDA tensor causes fork bomb

### ISSUE THREAD

**Issue by dhroth** [ray-project/ray#5529]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.3 LTS
- **Ray installed from (source or binary)**: pip install
- **Ray version**: 0.7.3
- **Python version**: 3.6.8
- **Exact command to reproduce**: CUDA_VISIBLE_DEVICES=0 python forkbomb.py

### Describe the problem
Running the following code causes dozens of ray_worker processes to be instantiated on the GPU. Usually, a long stream of CUDA out of memory errors are eventually printed (though sometimes this code doesn't print any errors):
```
import ray 
import torch

tensor = torch.ones(1).cuda()

@ray.remote(num_gpus=1.0)
def forkbomb():
    global tensor 
    tensor += 1
    return torch.zeros(1).cuda()

if __name__ == "__main__":
    ray.init(redis_password='forkforkfork')
    print(ray.get(forkbomb.remote()))
```
CC @kiddyboots216 

### Source code / logs
Log:
```
$ CUDA_VISIBLE_DEVICES=0 python forkbomb.py
2019-08-24 04:16:14,353 INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-08-24_04-16-14_352753_5738/logs.
2019-08-24 04:16:14,558 INFO services.py:409 -- Waiting for redis server at 127.0.0.1:16781 to respond...
2019-08-24 04:16:14,784 INFO services.py:409 -- Waiting for redis server at 127.0.0.1:19543 to respond...
2019-08-24 04:16:14,787 INFO services.py:809 -- Starting Redis shard with 10.0 GB max memory.
2019-08-24 04:16:14,989 INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-08-24_04-16-14_352753_5738/logs.
2019-08-24 04:16:14,990 WARNING services.py:1301 -- Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` whe
n calling ray.init() or ray start.
2019-08-24 04:16:14,990 INFO services.py:1475 -- Starting the Plasma object store with 20.0 GB memory using /dev/shm.
2019-08-24 04:17:04,747 ERROR worker.py:1714 -- Failed to unpickle the remote function '__main__.forkbomb' with function ID c05395f2915bf720b1276f0a06d7aed013c
42c85. Traceback:
Traceback (most recent call last):
  File "/data/drothchild/virtualenvs/pytorch/lib/python3.6/site-packages/ray/function_manager.py", line 424, in fetch_and_register_remote_function
    function = pickle.loads(serialized_function)
  File "/data/drothchild/virtualenvs/pytorch/lib/python3.6/site-packages/torch/storage.py", line 134, in _load_from_bytes
    return torch.load(io.BytesIO(b))
  File "/data/drothchild/virtualenvs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/data/drothchild/virtualenvs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 573, in _load
    result = unpickler.load()
  File "/data/drothchild/virtualenvs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 536, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/data/drothchild/virtualenvs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 119, in default_restore_location
    result = fn(storage, location)
  File "/data/drothchild/virtualenvs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 99, in _cuda_deserialize
    return storage_type(obj.size())
  File "/data/drothchild/virtualenvs/pytorch/lib/python3.6/site-packages/torch/cuda/__init__.py", line 615, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA error: out of memory
```
Followed by the exact same error (failed to unpickle, with a CUDA OOM stack trace) many times.

Also this error appears once among the OOM errors:
```
Traceback (most recent call last):
  File "forkbomb.py", line 14, in <module>
    print(ray.get(forkbomb.remote()))
  File "/data/drothchild/virtualenvs/pytorch/lib/python3.6/site-packages/ray/worker.py", line 2247, in get
    raise value
ray.exceptions.RayTaskError: ray_worker:__main__.forkbomb() (pid=35782, host=atlas)
Exception: This function was not imported properly.
```

If forkbomb() takes an argument (otherwise no change), I get this error instead of the one just above
```
Traceback (most recent call last):
  File "forkbomb.py", line 15, in <module>
    print(ray.get(forkbomb.remote(False)))
  File "/data/drothchild/virtualenvs/pytorch/lib/python3.6/site-packages/ray/worker.py", line 2247, in get
    raise value
ray.exceptions.RayTaskError: ray_worker:__main__.forkbomb() (pid=6196, host=atlas)
TypeError: f() takes 0 positional arguments but 1 was given
```
And then after all the errors, it prints the final answer correctly:
```
tensor([0.], device='cuda:0')
```

**Comment by ericl** [comment]
This is solved by @pcmoritz 's patch that prevents serialization of cuda tensors right?

In general, you should avoid sending torch tensors around. Converting them explicitly to/from numpy is the way to go.

**Comment by dhroth** [comment]
No -- I get the same behavior with the patch. His patch fixed it for you? Only difference is that on the occasions when it doesn't OOM after spawning dozens of ray_worker processes, it now throws Philipp's error instead of printing out the correct answer.

Also, I get the same behavior even if forkbomb() returns a regular tensor, so you can change the MWE above accordingly. The key is the global CUDA tensor.

When you say I "should" avoid giving torch tensors to Ray, does that mean that Ray has chosen not to support torch tensors? That wasn't my understanding based on our presentation at the Friday meeting.

**Comment by ericl** [comment]
The issue is the cuda tensor is getting serialized as part of the globals,
maybe somehow it's avoiding the check since the entire closure is
cloudpickled.

I would avoid sending any non numpy types around, it's asking for trouble.

**Comment by kiddyboots216** [comment]
Ray has inconsistent behavior in serializing/deserializing torch tensors. The patch doesn't fix this issue.

Forcing the user to manually call .cpu().detach().numpy() -> torch.from_numpy().cuda() every time they want to communicate a tensor between CUDA devices doesn't seem like a good solution.

**Comment by ericl** [comment]
How about we ban serialization of torch Tensors?

**Comment by richardliaw** [comment]
torch tensor serialization now works.
